(async function main(){if("gats.io"!=location.host&&"gats2.com"!=location.host)return alert("This inject can only be ran on gats.io!");if("function"!==typeof a41)return setTimeout(main);let ca="alignItems",Pc="background",P="backgroundColor",td="backgroundImage",U="border",Ka="borderBottom",Ce="borderColor",Qc=
"borderLeft",va="borderRadius",De="borderRight",Tb="borderTop",ud="borderWidth",La="color",x="display",Ee="flexDirection",vd="fontFamily",Ub="fontSize",Rc="fontWeight",wd="gridTemplateColumns",y=
"height",N="justifyContent",lb="left",Fe="marginBottom",Sc="marginLeft",Tc="marginRight",lc="marginTop",Ge="maxWidth",He="minWidth",Ie="outline",xd="overflowY",vb="right",wa="padding",Va=
"paddingBottom",Vb="paddingLeft",yd="paddingRight",Ta="paddingTop",xa="position",wb="top",mc="userSelect",Je="verticalAlign",zd="whiteSpace",w="width",Wb="zIndex",qa="#000f",Uc="#000c",Ke=
"#33dc",Le="#4448",Me="#6666",Ne="#777f",Oe="#80f8",Ad="#888f",Bd="#888c",Xb="#8888",Vc="#f00c",Pe="#f80f",Qe="#f80c",Yb="#ffff",Re="#ff0c",Wc="#fff8",xb=
"#fffc",Se="#008c",Te="#00fc",Ue="#800c",Ve="#0f0c",We="#666f",Xe="#8886",Cd="#ff0f",Ye="auto"+" auto".repeat(9),Ze="auto"+" auto".repeat(4),$e="10",Q="100%",af="calc("+Q+" - 15px)",bf=
"calc("+Q+" - 10px)",cf="calc("+Q+" / 3)",df="2em",Dd="-5px",da="0px",ef="1px",yb="2px",nc="3px",ff="3.5px",oc="4px",I="5px",Jb="7px",gf="8px",fb="10px",hf=
"14px",Ed="15px",jf="16px",pc="20px",Fd="25px",Gd="26px",Kb="28px",Wa="30px",mb="34px",kf="38px",Ma="40px",lf="43px",Hd="45px",mf="50px",Id=
"55px",Jd="60px",nf="70px",of="80px",pf="250px",qf="300px",rf="350px",sf="520px",Kd="linear-gradient(to bottom, "+Ue+" 0%, "+Vc+" 40%, "+Te+" 60%, "+Se+" "+Q+")",gb=" solid ",tf=nc+gb+Yb,Ca=oc+gb+Yb,Xc=
ff+gb+qa,uf=ef+gb+qa,ea=yb+gb+qa,Zb=nc+gb+qa,Lb=oc+gb+qa,Ld="absolute",Yc="bold",Md="block",D="center",Nd="Consolas",H="flex",vf="flex-end",Od="grid",$b="none",Da=
"relative",wf="row",Pd="pre-wrap",Qd="scroll",Na="space-between",nb="text",xf="inline-block",Zc=["Menu;Navigation;You can select any menu from the main menu by clicking on the menu's name.;Back Button;You can return to the menu selection screen by clicking the back button at the top left corner.;Toggling;You can toggle the menu to make it vanish or reappear by pressing (T) on your keyboard at any particular time.;Scrolling;You can scroll in some menus by either using your mouse wheel or moving the scroll bar at the right side of the menu.;Moving;You can drag the menu around by holding the title element.".split(";"),
"Settings;Toggles and Values;You can toggle On/Off settings by simply clicking on them. You can change Value settings by clicking the [+] or [-] buttons next to them or by using your scroll wheel on the value display. To know what a setting does, hover over the setting, since most controls have tooltips added.;Special Controls;Some menus use custom controls like text inputs, perk selection and more. Though most of those special controls don't need an introduction (as I think it is self explanatory enough, correct me if i'm wrong), but for Auto Upgrade, you can click a perk you have already selected to unselect it.;Empty Menus;Some menus (Recorder) don't have menu contents, which means they will be eventually added, probably...;Imperfect Features;Some features may decrease your effectiveness or may cause other issues, please report the issues if that is the case.;Saving;When you change any setting, it gets saved, which means if you reload, the settings won't be lost!".split(";"),
["Contact","Discord","We have a discord where you can talk with fellow TioHax users and even the Developer himself! https://discord.gg/CwWd5UKf6R"]],yf=["Developing;Main Developer of this Cheat Software;Taureon;For helping with technical stuff;Vaakir & Nitrogem35;Providing an API for the FFA Clan Display feature;Nitrogem35".split(";"),["Playtesting","Finding dumb bugs and general playtesting","Ravgo"],["Inspiration","Making my own Cheat Client","Vaakir","Providing me with moral justifications","GodF4ther, cat421, CrimAnn, SHTURM, DeadForYears and pretty much the rest of the Gats.io Community, you toxic idiots"],
["Special Thanks","You!","For using this cheat! Thank you so much!"]],f=j58,K=void 0,{PI:Rd,abs:Sd,asin:$c,atan2:ab,ceil:zb,cos:ma,floor:Td,max:ob,min:hb,random:Ud,round:fa,sign:qc,sin:ha,sqrt:Ea,E:zf}=Math,Oa=2*Rd,ia=Oa/360,ad=ha(60*ia),Ab=1/3,ra={x:0,y:0},ac=0,bc=0,Vd,Af={noArmor:0,lightArmor:1,mediumArmor:2,heavyArmor:3},rc={pistol:0,smg:1,shotgun:2,assault:3,sniper:4,lmg:5,"bolt-action-rifle":4,"machine-gun":5},Bf="Pistol SMG Shotgun Assault Sniper LMG".split(" "),pb=
[24,22,24,24,30,24,7,Infinity],sc=[44,50,55,63,75,62,0,0],bd=[18,13,10,18,22,16,32,Infinity],Pa=0,Wd=0,V={x:0,y:0,isPressed:0,isShooting:0},tc=3,uc=[],vc={},sa=";Guide;Menu;Aimbot;ESP;Instant Chat;Misc;Player Manager;Auto Upgrades;Chat Spammer;Anti Aim;Perk Hacks;Paint;Recorder;Discord Rich Presence;THNet;Weird;Advanced;Credits".split(";"),wc={a:["Enable Aimbot","Automatically aims your weapon at enemies, toggleable with right click."],b:["Aim Smoothing","Makes aimbot's movement smoother."],c:["Enable",
"Whichever is closest to your cursor."],d:["Use Acceleration","Tries to account for the enemy's velocity changes."],e:["Ignore Chatting","Ignores players who are typing."],f:["Ping Compensation","Tries to compensate for the internet connection."],g:["Enable","Shoots automatically when possible, requires Wall Check to be enabled (not recommended with single fire weapons.)"],h:["Wall Check","Tries to not aim at enemies behind walls."],i:["Use Ahead Check","Use the position of where the enemy will be for wall check instead of where they are right now."],
j:["Dash Disable","Turns aimbot temporarily off when dashing."],k:["Range","How close an enemy needs to be to be targetted by the aimbot when in Cursor Proximity mode."],l:["Prioritise Targets","Prioritises targetted players over anything when applicable."],m:["When Mouse Down","Triggerbot fires only when you shoot, suppresses manual firing when this and Triggerbot is enabled."],n:["Rightclick Friend","When you Rightclick on someone, it adds them to the friends list."],o:["Middleclick Target","When you Middleclick on someone (Mouse-wheel when you press on it), it adds them to the targets list."],
v:["Targets Only","Ignores people you aren't targetting."],w:["Avoid Friends (WIP)","Avoids shooting at an enemy if it would be too risky for a friend on the enemy team to get hit. THIS IS IN BETA, MAY RESULT IN UNINTENDED CONSEQUENCES."],x:["Ahead Calc Depth","The accuracy of the calculation that checks how far ahead the aimbot should aim."],y:["Prioritise Leader","Prioritises the top scoring player if they are on the enemy team. This takes priority over the 'Prioritise Targets' setting."],p:["General",
""],q:["Enhancements",""],r:["Cursor Proximity",""],s:["Smarter Targeting",""],t:["Priority",""],u:["Triggerbot",""]},xc={a:["Extended View","Gives you maximum possible vision"],b:["Fixed Camera","Stops the camera from moving"],c:["Player Tracers","Draws a line from you to every player currently loaded in"],d:["CursorProx Tracers","When Cursor Proximity is enabled, draws lines from your cursor to your enemies"],e:["Wall Check Tracers","Visualises the wall checking algorithm"],f:["Gun Tracers","Draws the line a bullet would go if you shot your gun"],
g:["Grenade Tracers","Draws a line to where a grenade is to where the grenade will roughly land at"],h:["Show Invisibles","Shows silencers, camo players and landmines"],i:["Reveal Teams","Reveals the team affiliations for grenades, landmines, gas and knifes"],j:["Healths","Shows every players' current health"],k:["Armors","Shows every players' current armor"],l:["Magazines","Shows every players' current ammo counts"],m:["Gun Reload","Shows every player's current gun reloading status with a percentage."],
t:["Ranges","Shows how far players can shoot (may cause the game to look like a clusterfuck)"],n:["Camera Cursor Fix","When Aimbot is on, this makes the Camera follow your Cursor, and not where the Aimbot tells the game where the Cursor is"],o:["Self Attributes","Makes Player Healths, Player Armors, Player Magazines and Player Gun Status draw over you aswell"],u:["Zoom Sensitivity","When the 'Extended View' mode is on 'Scroll', this determines how much you zoom in and out when you use the scroll wheel"],
p:["Camera","Various Camera Improvement Settings"],q:["Tracers","Some Lines and Circles"],r:["Player Attributes","Helpful Attributes of nearby Players"],s:["Other","Other ESP Features"]},Xd=[["Auto Upgrade","Automatically upgrades specified perks for you"],"No Perk Selected"],yc={0:["Toggle Scroller","Turn the Chat Scroller either On or Off"],b:["Text Width","Maximum width of the scrolled text"],d:["Direction","In which direction the text scrolls (- = left, + = right)"],c:["Interval","The interval it takes for the text to shift"],
h:["Pause Period","When something besides the Scroller has said something in chat, for how long it should wait before it should scroll again"],a:["Text","The Text to scroll in Chat"],e:["Seperator","The Seperator so it does not look like 'hello worldhello worldhello world'"],j:["Prefix","Static text to add in front of your chat message"],k:["Sufffix","Static text to add after your chat message"]},cd={0:"Change the text you say when you press a key",a:["Chat Binds","Press buttons to make the cheat instantly say something in chat for you"],
b:["Edit Binds","Select a button on your keyboard to make the cheat say LITERALLY ANYTHING for you"],c:["On Kill Chat Msg","Say something when you kill someone"],d:["","Change the text you say when you kill someone"],e:["On Death Chat Msg","Say something when you die"],f:["","Change the text you say when you die"],g:["Auto Medkit Thank","Instantly say thanks when you get healed"],h:["","Change the text you say when you get healed"]},Yd={a:["While Reloading","To hide aim while reloading your gun"],
b:["While Shooting","To hide aim while shooting your gun"],c:["While Idle","To hide wim while neither shooting or reloading your gun (not recommended with single fire weapons)"],d:["Min Angle","Minimum Angle where it starts off"],e:["Angle Range","Random additional angle from 0 to the angle range which gets added on the Minimum Angle"],f:["Spin Speed","How fast it spins. Accepts negative numbers if you want it to spin the other direction"],g:["Interval","The amount of time (in game ticks) at which it picks another position to aim at"],
j:["Draw Real Aim","Draws the gun a second time as if Anti Aim wasn't enabled"]},dd={a:["Auto Reload","Automatically reloads when there are no enemies nearby"],b:["Ping Display","Displays the latency to the server"],c:["FPS & Render Time","Displays your current FPS and how long it took to render the last frame"],d:["Static Hud","Disables hud animations"],e:["Static Health","Disables the hp moving animations on players when they take damage"],f:["No Unload Popup","Disable the unload popup when you leave or reload the game"],
g:["Better Crate HP","Makes the health display pick colors better instead of just picking one of 5 colors"],h:["Hide Chatbox","Others won't see that you're typing, they'll just see you not move"],i:["FFA Clan Tags","Shows clan tags next to names in FFA Mode"],j:["Feature Display","Shows what main features are enabled in the bottom right corner"],o:["Coordinates","Shows your coordinates, velocity and acceleration"],p:["Leaderboard Badges","Shows Friends, Targets, THNet members and the dev with badges next to their leaderboard"],
k:["In Game","Gameplay related settings"],l:["Debug","Special Technical Information"],m:["Heads Up Display","HUD-related settings"],n:["Other","Settings that have no category of their own"]},zc=[["Friends","Switch to the list of ignored enemies"],["Targets","Switch to the list of prioritised targets"],["Muted","Switch to the list of muted players"],["Add a friend","Add a target","Mute someone"]],Bb={0:["Disconnect","Disconnect from the current server"],1:["Clear Bootloader","Clears the stored code and version of the bootloader"],
a:["Ping Cache","How many recent ping times it stores"],b:["Aim Constant","Lower = Aimbot aims further ahead"],e:["Account for ping","How far the aimbot aims ahead depending on the ping. lower = further"],c:["Sync TPS with Server","Makes the game run at 25 ticks per second instead of 62.5"],d:["Optimise Wallcheck","Optimises the checking for the wall checking algorithm"]},Xa={0:["KnifeBot (WIP)","Automatically shoots a knife at very near enemies"],1:["ShieldBot (WIP)","Automatically blocks nearby bullets"],
2:["Medkit and Build (WIP)","Gives tools for using Medkit and Build perks"],a:["Enable","Automatically shoots a knife at a close enemy"],b:["Range","How close an enemy needs to be to be knifed"],d:["Enable","Automatically block nearby bullets"],e:["Takedown delay","How long (in ticks) the shield should be up for even when the bullet is deflected"],g:["Manual Ability","Does not take control over your ability to use the shield, but still aims torwards close bullets for you"],i:["Lookahead","Tries to block incoming bullets earlier the higher this value is"],
l:["Visualiser","For debugging purposes, visualises the check that the ShieldBot does."],h:["Placement Vision","Where exactly the build block or medkit will be placed when Build or Medkit is used"],j:["Auto Self Heal","Automatically puts the Medkit in front of you if you're below a certain health threshold"],k:["Threshold","The health threshold that says when to heal yourself. If your health is lower, it heals"]},Cb={0:["THNet Rules","Rules you have to follow when using THNet"],1:["Don't kill other THNet members, the point is to make THNet work with each other.",
"Don't spam THNet Chat with garbage, else it drowns out good messages.","Don't be mean to others in THNet Chat, it does not make you a good person."],b:["Connect","Connects to THNet when you join a server, bringing a variety of features"],c:["Disconnect","Disconnect from THNet, your Aimbot will shoot at them but their Aimbots will also shoot you"],d:["THNet Members","The List of THNet Members in your current lobby"],e:["Serverwide Chat","Chat with all other THNet members in your current server without needing to be close"],
f:["Donate Connection","Donate an unused Game Connection to Taureon for a Botnet which will assist you"],h:["THNet Admin Authentication","Authentication Code Input Box for THNet Administrators"],j:["Share Gameplay Info","Shares health, position, ammo count and class with other members"]},Cf={a:["Move with Cursor","You will move to where your cursor is"]},Ya={0:["Reset Colors/Values","Resets every change back to default"],1:["ARE YOU SURE that you want to reset everything you have changed in Paint?",
"Type exactly 'yes' if yes"],a:["Grid","Change the look of the floor"],n:["Capture Points","Change the look of capture points"],h:["Crates","Change the look of crates on the map"],b:["Horiz. Space","The horizontal space between the grid lines"],c:["Vert. Space","The vertical space between the grid lines"],d:["Hori. Line Width","Width of the lines that go horizontally"],e:["Vert. Line Width","Width of the lines that go vertically"],g:["Grid Color","The color of the Grid"],o:["No One Capturing","The color if no one is capturing the point"],
p:["FFA You Capturing","The color if you are capturing the point"],q:["Blue Capturing","The color if the blue team is capturing the point"],r:["Red Capturing","The color if the red team is capturing the point"],s:["Edge Width","How wide the edges of the capture points should be"],m:["Health Display","Change which parts should turn white when build crates get damaged"],i:["Square Crates","The large square-shaped crates"],j:["Long Crates","The smaller rectangle-shaped crates"],k:["Build Crates","The crates made with the Build perk"],
l:["Premium Crates","Build crates but built by Premium Users"],t:["Crate Corpses","The colors the crate takes on as its Health decreases"]},Ac=[[["Normal","Normal Game View"],["Scroll","Use your scroll wheel to change how much you can see"],["Static","Automatically zooms out to the most possible you can see"]],[["None","Crate colors do not change"],["Edges","Only the crate's edge changes"],["Inside","Only the inside of the crate changes"],["Both","Entire crate changes"]],[["Disabled","No Display for what Main Features are enabled"],
["Enabled","Main Features get displayed in the bottom right corner"],["Graytext","Subsettings are shown in Gray Colors instead of Rainbow"]],[["None","No ShieldBot check visualisers"],["Closeness","The circle inside a bullet needs to be in"],["Bullets","Draws small arrows to see how far ahead it predicts the bullets to be"],["Both","Shows both Bullets and Closeness"]]],ed=["Minimise the Menu, can be reopened by pressing T","Return back to the previous menu","Close THNet chat, can be reopened by pressing CTRL"],
fd={},bb=[],cb=[],Bc=[],cc=0;var qb=0,rb=0,Db=0,db=0,Eb=0;let gd=1,hd=0,R={a:27,b:65,c:69,d:68,e:82,f:83,g:84,h:87,i:90,j:13,k:32,l:37,m:39,n:38,o:40,p:78,q:16,r:17},ja=[0,"","",""],id="bipod optics thermal armorPiercing extended grip silencer lightweight longRange thickSkin".split(" "),Mb="shield firstAid grenade knife engineer ghillie dash gasGrenade landMine fragGrenade".split(" "),Df={bipod:"No Recoil",optics:"Binoculars",thermal:"Thermal",armorPiercing:"Damage",extended:"Large Mags",grip:"+Accuracy",
silencer:"Silencer",lightweight:"Speed",longRange:"Range",thickSkin:"Kevlar",shield:"Shield",firstAid:"Medkit",grenade:"Grenade",knife:"Knife",engineer:"Build",ghillie:"Camo",dash:"Dash",gasGrenade:"Gas",landMine:"Landmine",fragGrenade:"Frag"},n={a:0,b:0,c:0,k:200,d:0,e:0,f:0,h:0,i:0,j:0,g:0,m:0,l:0,n:1,o:1,w:0,x:0,y:0},q={a:0,b:0,n:0,c:0,d:0,e:0,f:0,g:0,h:0,i:0,j:0,k:0,l:0,m:0,t:0,o:0,u:1.1},u={a:"TioHax on top! https://cheats.gatsio.repl.co/",f:0,b:30,g:0,c:100,i:0,d:1,e:" # ",h:3E3,j:"",k:""},
W={c:0,d:"[[ENEMY]] just died to TioHax!",e:0,f:"[[ENEMY]] = god awful",g:0,h:"I have been healed! Thank you!",a:0,b:{[R.c]:"I need a medic!",[R.i]:"Put Build Blocks here!"}},B={a:0,b:0,c:0,d:0,e:0,f:0,g:1,h:0,i:0},Cc={a:0,d:0,b:[],c:[],e:0,f:-1},L={a:0,b:0,c:0,d:0,e:0,f:0,g:0,h:0,i:0,j:0,o:0,p:0},E={a:10,b:1,c:2.5,d:1,e:25},p={c:0,a:0,b:100,d:0,e:5,f:0,g:0,i:0,h:0,j:0,k:50,l:0},t={b:1,a:0,e:0,f:0,i:"",h:"",l:[],j:0,k:{},g:0},dc={a:0},Ef={a:0,b:"State",c:"Details",d:30,e:Date.now(),f:0,g:0,j:"1050361019609927690",
h:0,i:"",k:[]},v={b:20,c:20,d:1,e:1,g:["#e3e3e8","#efeff5"],o:["#aaaaaa","#f9f9f9"],p:["#00cc66","#f9f9f9"],q:["#8dd8f8","#f9f9f9"],r:["#f26740","#f9f9f9"],s:4,m:2,i:["#808080","#dfbf9f"],j:["#808080","#bec8dd"],k:["#808080","#53c68c"],l:["#2e2d2d","#f0ba37"],t:["#ffffff","#ffffff"]},C={a:0,b:0,c:0},Nb=[],l=parseInt,Za=a=>document.getElementById(a),J=(a,b,c)=>RF.list[a]?.send(a59("key-press",{inputId:b,state:1*c})),Zd=a=>{let b=0,c;for(c=0;c<a.length;c++)b=(b<<5)-b+a.charCodeAt(c)|0;return b},
Ff=a=>new Promise(b=>fetch("https://cheats.gatsio.repl.co/"+a).then(c=>c.text()).then(b)),ka=(a,b,c)=>isNaN(b)?a:hb(c,ob(a,b)),Qa=(a,b=3)=>{for(a=a.toString();a.length<b;)a=" "+a;return a},Fb=(a,b,c)=>{c||Gf();hd=b.length;RF.list[a].send(a59("message",{message:b.replace(/,/g,"~")}))},sb=a=>a.replace(/\[[\d\w]{1,4}\] /,""),jd=(a,b)=>{for(let c=0;c<a.length;c++)if(a[c]==b)return c;return-1},la=(a,b)=>{for(let c=0;c<a.length;c++)if(a[c]==b)return 1;return 0},na=a=>Object.values(a.pool),
Fa=()=>{J(C.a,6,V.isShooting=0);for(let a of Nb)a();localStorage.setItem("TioHax_settings",JSON.stringify([bb.filter(a=>!a.startsWith("Guest ")),cb.filter(a=>!a.startsWith("Guest ")),ja,[n.a,n.b,n.c,n.d,n.e,n.f,n.g,n.h,n.i,n.j,n.k,n.l,n.m,n.n,n.o,n.v,n.w,n.x,n.y],[q.a,q.b,q.c,q.d,q.e,q.f,q.g,q.h,q.i,q.j,q.k,q.l,q.m,q.n,q.o,q.t,q.u],[u.a,u.b,u.c,u.d,u.e,u.j,u.k],[B.a,B.b,B.c,B.d,B.e,B.f,B.g,B.j],[W.a,W.b,W.c,W.d,W.e,W.f,W.g,W.h],[L.a,L.b,L.c,L.d,L.e,L.f,L.g,L.h,L.i,L.j,L.o,L.p],[E.a,E.b,E.d,E.c,E.e],
[t.b,t.e,t.f,t.j],Bc.filter(a=>!a.startsWith("Guest ")),[p.a,p.b,p.d,p.e,p.g,p.h,p.i,p.j,p.k,p.l],[],[v.b,v.c,v.d,v.e,v.g,v.o,v.p,v.q,v.r,v.s,v.m,v.i,v.j,v.k,v.l,v.t],[C.a,C.b,C.c]]))},kd=(a,b,c,e,d,g)=>{f.strokeStyle=g;f.lineWidth=d;f.beginPath();f.moveTo(a,b);f.lineTo(c,e);f.stroke()},ec=(a,b,c,e,d)=>kd(a.x,a.y,b.x+c.x,b.y+c.y,e,d||Dc(b)),Gb=(a,b,c,e,d)=>kd(a.x+c.x,a.y+c.y,a.x+c.x+b.x,a.y+c.y+b.y,e,d||Dc(a)),ya=(a,b,c,e,d)=>{f.strokeStyle=d||Dc(a);f.lineWidth=e;f.beginPath();f.moveTo(a.x+b.x+c,
a.y+b.y);f.arc(a.x+b.x,a.y+b.y,c,0,Oa);f.stroke()},$a=(a,b,c,e)=>{f.fillStyle=e;f.lineWidth=1;f.strokeStyle="#000";f.fillText(c,a,b);f.strokeText(c,a,b)},Ec=(a,b,c,e,d,g)=>c<=ob(a,d)&&c>=hb(a,d)&&e<=ob(b,g)&&e>=hb(b,g),Fc=(a,b,c,e,d,g)=>(a=(e-b)*(d-c)-(c-a)*(g-e))?0<a?1:2:0,$d=(a,b,c,e,d,g,h,m)=>{let T=Fc(a,b,c,e,d,g),A=Fc(a,b,c,e,h,m),za=Fc(d,g,h,m,a,b),ib=Fc(d,g,h,m,c,e);return T!=A&&za!=ib?1:0==T&&Ec(a,b,d,g,c,e)||0==A&&Ec(a,b,h,m,c,e)||0==za&&Ec(d,g,a,b,h,m)||0==ib&&Ec(d,g,c,e,h,m)},ae=(a,b,c,
e,d,g)=>{if(a===c&&b===e)return(d-a)**2+(g-b)**2;let h=ob(0,hb(1,((d-a)*(c-a)+(g-b)*(e-b))/((d-a)**2+(g-b)**2)));return(d-(a+h*(c-a)))**2+(g-(b+h*(e-b)))**2},ld=(a,b,c)=>{o3[c]=b;RF.list[a].send(a59("upgrade",{upgrade:b,upgradeLevel:c}));c8[c]=0},Dc=a=>a.ownerId&&!a.teamCode?RD.pool[c3].id==a.ownerId?"green":"red":2==a.teamCode?"blue":1==a.teamCode?"red":{"#f26740":"red","#f6803c":"orange","#fff133":"yellow","#92cd8b":"green","#8dd8f8":"blue","#f7b0c2":"hotpink"}[a.color.a],Hb=(a,b)=>{b=sb(b);let c=
jd(a,b);-1==c?a.push(b):c==a.length-1?a.pop():a[c]=a.pop();Fa()},Ob=(a,b)=>{for(let c in b)a[c]=b[c];return a},Ua=(a,b)=>Ob(a.style,b),r=(a,b={},c={},e=[])=>{a=document.createElement(a);Ob(a.style,b);Ob(a,c);for(let d of e)a.append(d);return a},md=()=>{},be=a=>{clearTimeout(u.g);u.g=0;let b=()=>{let c=u.a+u.e,e=u.f,d=u.b-(u.j.length+u.k.length),g=c.length?"":" ",h=" ".repeat(u.i);if(!g)for(let m=0;m<d;m++)g+=c[(e+m)%c.length];Fb(a,h+u.j+g+u.k+h,1);u.f=(e+u.d+c.length)%c.length;u.i=(u.i+1)%3;u.g=setTimeout(b,
u.c)};b()},Gf=a=>{if(u.g){clearTimeout(u.g);u.g=0;var b=Ud();Vd=b;setTimeout(()=>Vd==b&&be(a),u.h)}},nd=a=>{for(;a.hasChildNodes();)a.removeChild(a.lastChild)},od=(a,b,c)=>{a=Db.scrollHeight>Db.clientHeight;b=Db.lastChild;c=b.style;Ua(b,{[Ka]:a?da:ea,[y]:l(c.height)-(4-2*l(c.borderBottom||c.border))+"px"})},Ga=a=>fd[a]??a,fc=(a,b)=>r("div",{[w]:Q,[y]:Ma,[x]:H,[ca]:D,[Vb]:I,[yd]:I,[Ka]:ea,[Va]:da,[N]:Na},{title:Ga(a[1])},[r("div",{},{innerText:Ga(a[0])}),b]),pd=(a,b)=>fc(a,r("div",{[w]:Hd,[y]:Wa,
[U]:Ca,[xa]:Da,[va]:Jb,[P]:Ke},{onclick:()=>{Fa();b()}})),ta=(a,b,c)=>{let e=r("div",{[w]:Jd,[y]:Wa,[U]:Ca,[x]:H,[xa]:Da,[ca]:D,[va]:Jb,[N]:D},{onclick:()=>{b();e.G();Fa()},G:()=>{let d=c();e.innerText=d?"On":"Off";Ua(e,{[P]:d?Ve:Vc})}});e.G();Nb.push(e.G);return fc(a,e)},Aa=(a,b,c)=>{var e={[w]:Wa,[y]:Wa,[U]:tf,[x]:H,[xa]:Da,[Rc]:Yc,[ca]:D,[va]:I,[N]:D,[P]:Re};let d=r("div",{[La]:qa,[w]:Jd,[y]:mb,[U]:Ca,[x]:H,[xa]:Da,[ca]:D,[Sc]:I,[Tc]:I,[va]:I,[N]:D,[P]:xb},{onwheel:h=>{h.preventDefault();b(qc(-h.deltaY));
d.G(1)},G:h=>{d.innerText=c();h&&Fa()}}),g=r("div",e,{innerText:"-",onclick:()=>{b(-1);d.G(1)}});e=r("div",e,{innerText:"+",onclick:()=>{b(1);d.G(1)}});d.G();Nb.push(d.G);return fc(a,r("div",{[x]:H,[ca]:D,[Ee]:wf},{},[g,d,e]))},Hf=(a,b,c)=>{let e=r("input",{[La]:qa,[w]:Q,[y]:mb,[U]:Ca,[x]:H,[xa]:Da,[ca]:D,[va]:I,[N]:D,[P]:xb},{type:nb,maxlength:64,onfocus:()=>Pa=1,onblur:()=>Pa=0,oninput:()=>{b(e.value);e.value=c();Fa()},value:c()});Nb.push(()=>e.value=c());return r("div",{[w]:Q,[wa]:I,[Ta]:da,[Ka]:ea,
[Va]:da,[N]:Na,[y]:of},{title:Ga(a[1])},[r("div",{[w]:Q,[x]:H,[wa]:I,[N]:Na,[y]:Ma},{innerText:Ga(a[0])}),e])},Gc=(a,b,c,e)=>{let d=0;for(let T in b)b[T][0].length>d&&(d=b[T][0].length);d=d+4.5+"ch";let g=e(),h=Object.keys(b).length;b[g]||c(g=0);let m=r("div",{[w]:d,[Ge]:d,[U]:Ca,[x]:H,[va]:Jb,[yd]:fb,[N]:vf,[P]:Oe,[Wb]:$e},{hidden:1,onclick:()=>{c(++g%h);m.G()},G:()=>Ob(m,{innerText:Ga(b[e()][0])+" \u25bc",title:Ga(b[e()][1])})});m.G();Nb.push(m.G);return fc(a,m)},If=(a,b)=>{let c={},e=[];for(let d in b){let g=
r("input",Ob(c,{[w]:Gd,[y]:Gd,[va]:Jb,[U]:uf,[wa]:da,[Ie]:Ca,[Sc]:Jb,[Tc]:I}),{type:"color",value:b[d],oninput:()=>{b[d]=e[d].value;Fa();e[d].G()},G:()=>Ua(g,{[P]:g.value=b[d]})});b[d]||(g.value="#ffffff",g.oninput());g.G();e[d]=g}return fc(a,r("div",{[x]:H},{},e))},tb=(a,b)=>{let c=r("div",{[x]:H},{innerText:Ga(a[0])}),e=r("div",{[w]:Hd,[y]:Wa,[U]:Ca,[x]:H,[xa]:Da,[ca]:D,[va]:Jb,[N]:D,[P]:Ad},{innerText:"\u25bc",onclick:()=>od(e.innerText=(d.hidden=!d.hidden)?"\u25bc":"\u25b2")});a=r("div",{[w]:Q,
[wa]:I,[x]:H,[Va]:da,[N]:Na,[P]:Me,[y]:Ma},{title:Ga(a[1])},[c,e]);let d=r("div",{[Tb]:ea,[Qc]:Lb,[Ka]:Lb},{hidden:1},b);return r("div",{[Ka]:ea},{},[a,d])},Pb=a=>{md=()=>{};Nb=[];nd(Db);Hc[a][1](b=>Db.append(b));od()},Jf=(a,b,c)=>{let e={},d,g=r("div",{[lb]:I,[w]:rf,[La]:Yb,[U]:ea,[va]:I,[Wb]:tc++,[xa]:Ld,[Ub]:pc,[vd]:Nd,[mc]:$b},{},[a=r("div",{[w]:Q,[y]:lf,[U]:ea,[wa]:I,[x]:H,[zd]:Pd,[N]:Na,[td]:Kd},{innerText:a,onmousedown:h=>{let m=qb.style;m[Wb]=tc++;m[vb]&&(m[lb]=window.innerWidth-(l(m[vb])+
l(m[w]))+"px",m[vb]="");e.offsetX=h.clientX-l(m[lb]);e.offsetY=h.clientY-l(m[wb]);e.enable=1},onmouseup:()=>e.enable=0},[r("div",{[La]:qa,[w]:Kb,[y]:Kb,[U]:Xc,[x]:H,[Rc]:Yc,[ca]:D,[Ta]:Dd,[va]:fb,[N]:D,[P]:Wc},{title:fd[b]??b,innerText:"_",onclick:()=>qb.hidden=1})]),b=r("div",{[w]:Q,[y]:sf,[U]:ea,[xd]:Qd,[Tb]:ea,[Qc]:ea,[P]:Uc})]);c&&(d=r("div",{[La]:qa,[w]:Kb,[y]:Kb,[U]:Xc,[x]:H,[ca]:D,[N]:D,[P]:Wc,[va]:fb},{title:fd[c]??c,innerText:"<",onclick:()=>Pb(0)}),a.prepend(d));e.element=g;uc.push(e);return[g,
a,b,d]},Kf=()=>{let a={};Eb=r("input",{[La]:qa,[w]:Q,[y]:mb,[U]:Ca,[x]:H,[xa]:Da,[ca]:D,[va]:I,[N]:D,[P]:xb},{type:nb,maxlength:128,onfocus:()=>Pa=1,onblur:()=>Pa=0,onchange:()=>{t.a?.send("0 "+Eb.value);Eb.value="";Eb.blur()},value:""});document.body.append(db=r("div",{[vb]:I,[La]:Yb,[w]:qf,[U]:ea,[Wb]:tc++,[xa]:Ld,[Ub]:pc,[vd]:Nd,[mc]:$b,[va]:I},{hidden:1},[r("div",{[w]:Q,[y]:Ma,[U]:ea,[x]:H,[wa]:I,[zd]:Pd,[Vb]:fb,[N]:Na,[td]:Kd},{innerText:"THNet Serverwide Chat",onmousedown:b=>{let c=db.style;
c[Wb]=tc++;c.right&&(c[lb]=window.innerWidth-(l(c[vb])+l(c[w]))+"px",c[vb]="");a.offsetX=b.clientX-l(c[lb]);a.offsetY=b.clientY-l(c[wb]);a.enable=1},onmouseup:()=>a.enable=0},[r("div",{[La]:qa,[w]:Kb,[y]:Kb,[U]:Xc,[x]:H,[Rc]:Yc,[ca]:D,[Ta]:Dd,[va]:fb,[N]:D,[P]:Wc},{title:Ga(ed[2]),innerText:"_",onclick:()=>Fa(t.e=1-(db.hidden=1))})]),rb=r("div",{[w]:Q,[y]:pf,[U]:ea,[Ub]:hf,[xd]:Qd,[Tb]:ea,[mc]:nb,[Qc]:ea,[P]:Uc}),r("div",{[w]:Q,[x]:H,[wa]:I,[Ta]:yb,[Va]:da,[N]:Na,[P]:Uc,[y]:Ma},{},[Eb])]));Ua(db,
{[wb]:(window.innerHeight-l(rb.style[y]))/2+"px"});a.element=db;uc.push(a)},ce=()=>{for(let a of uc){let b=a.element,c=b.getBoundingClientRect(),e=b.style;e[vb]||Ua(b,{[lb]:ob(0,hb(window.innerWidth-c[w],l(e[lb])))+"px",[wb]:ob(0,hb(window.innerHeight-c[y],l(e[wb])))+"px"})}},Ra=(a,b,c)=>(a.x-c.x-b.x)**2+(a.y-c.y-b.y)**2,gc=(a,b,c,e,d=n.x)=>{d&&(c=Ra(a,gc(a,b,c,e,d-1),ra));d=b.x;let g=b.y;c=(Ea(c)-sc[e])/(pb[e]*E.b);n.f&&(c+=zb(RF.list[0].n/E.e));if(n.d){e=a.v?8*a.v:a.B;let h=a.w?8*a.w:a.C;c>(e-a.B)/
a.v?(d+=e*c-(e-a.B)**2/(a.v?2*a.v:Infinity),d+=h*c-(h-a.C)**2/(a.w?2*a.w:Infinity)):(d+=b.B*c+.5*a.v*c**2,d+=b.C*c+.5*a.w*c**2)}else d+=b.B*c,g+=b.C*c;return{x:d,y:g}},de=(a,b,c,e,d,g,h,m)=>{let T=n.v,A=n.c&&n.k?n.k**2:Infinity,za,ib,Ic,Ha={x:j9[0],y:j9[1]};for(let jb of c){c=Ra(a,jb,ra);n.c?(za=Ra(Ha,jb,b),q.d&&ec(Ha,jb,b,1,"#888")):za=c;if(n.h){var F=a,M=jb,ua=d,ba=m,oa=n.i?gc(F,M,Ra(F,M,ra),ba):M,S=oa.x-F.x,X=oa.y-F.y;X=ab(X,S)+$c(18/Ea(S**2+X**2));S=0-(.6*Oa+X);ba=sc[ba]+pb[ba]-14;X=0-(.75*Oa+
X);F={x:F.x+ha(S)*F.F+ha(X)*ba,y:F.y+ma(S)*F.F+ma(X)*ba};ba={x:(F.x+oa.x)/2,y:(F.y+oa.y)/2,z:Ea(Ra(F.x,oa.x,ra))/2};S=[[F,oa]];a:for(X=0;X<ua.length;X++){var Y=ua[X];if(Y.j&&!(Ra(ba,Y,ra)>(ba.z+Y.h)**2))for(var Ba=0;Ba<Y.f.length;Ba++)if($d(F.x,F.y,oa.x,oa.y,Y.x+Y.f[Ba][0],Y.y+Y.f[Ba][1],Y.x+Y.f[Ba][2],Y.y+Y.f[Ba][3])||$d(M.x,M.y,oa.x,oa.y,Y.x+Y.f[Ba][0],Y.y+Y.f[Ba][1],Y.x+Y.f[Ba][2],Y.y+Y.f[Ba][3])){S.push(Y);if(E.d)break a;break}}M=S;if(q.e){ua=M[0];f.globalAlpha=1<M.length?1:.5;kd(ua[0].x+b.x,
ua[0].y+b.y,ua[1].x+b.x,ua[1].y+b.y,2,"#888");f.globalAlpha=.5;for(ua=1;ua<M.length;ua++)M[ua].I();f.globalAlpha=1}if(1<M.length)continue}if(!(c<g||za>h||(M=la(cb,jb.u),T&&!M)||(n.l&&M&&!T&&(T=1,A=n.c?n.k**2:Infinity),za>A))){if(M=n.w)a:{M=a;F=jb;ua=e;oa=m;F=n.i?gc(M,F,Ra(M,F,ra),oa):F.getAttr();ba=F.x-M.x;S=F.y-M.y;X=ab(S,ba)+$c(18/Ea(ba**2+S**2));ba=0-(.6*Oa+X);S=sc[oa]+pb[oa]-14;X=0-(.75*Oa+X);ba={x:M.x+ha(ba)*M.F+ha(X)*S,y:M.y+ma(ba)*M.F+ma(X)*S};S=(S+bd[oa]*pb[oa])/Ea(Ra(M,F,ra));F.x*=S;F.y*=
S;for(S=0;S<ua.length;S++){X=ua[S];Y={x:-c2.x,y:-c2.y};Ba=X.F*Ea(ob(1,(Ra(M,X,ra)-Ra(M,ba,ra))/(2.5*pb[oa])));let Jc=ae(ba.x,ba.y,F.x,F.y,X.x,X.y)<Ba**2;ya(X,Y,Ba,2,Jc?"#888":"#aaa");if(Jc){M=1;break a}}M=void 0}M||(A=za,Ic=c,ib=jb)}}n.c&&(ib&&ec(Ha,ib,b,2,"#888"),a=Ea(A),f.beginPath(),f.moveTo(Ha.x+a,Ha.y),f.arc(Ha.x,Ha.y,a,0,Oa),f.stroke());return{D:ib,E:Ic}},ee=(a,b,c,e,d)=>{b.dashing||(b=gc(a,b,e,d));e=Ea(Ra(a,b,ra));50>e&&(e=50/e,b.x-=a.x,b.y-=a.y,b.x*=e,b.y*=e,b.x+=a.x,b.y+=a.y);return{clientX:b.x+
c.x,clientY:b.y+c.y}},fe=(a,b)=>{a.a=Zd(a.u=sb(a.s=a.t=b));"FFA"!=c22||a.s.startsWith("Guest ")||(a.t in vc?vc[a.t]&&(a.s="["+vc[a.t]+"] "+a.s):Ff("clanof/"+a.s).then(c=>{(vc[a.t]=c)&&(a.s="["+c+"] "+a.s)}))},ge=()=>{f.font="bold 20px consolas";let a=2*j1-5,b=c2?Td(1.725*j2):2*j2-30;var c=q.c||q.d||q.e||q.f||q.g,e=q.j||q.k||q.l||q.m||q.t;c=[[u.g,"Chat Spammer"],[L.i,"FFA Clan Display"],[u.g,"Chat Scroller"],[q.h||q.i,"Invis Reveal"],[L.a,"Auto Reload"],[p.a||p.d||p.h,"Perk Hacks",p.a?"KnifeBot":"",
p.d?"ShieldBot":"",p.h?"Build & Medkit":""],[B.a||B.b||B.c,"Anti Aim"],[n.a,"Aimbot",n.h?"Wall Check":"",n.v?"Targets Only":"",n.c?"Cursor Prox":"",n.g?"Triggerbot"+(n.m?", Mouse Down":""):""],[q.a||q.b,"Camera",q.a?"Zoom":"",q.b?"Fix":""],[c||e,"ESP",c?"Tracers":"",e?"Player Attributes":""],[t.b,"THNet",t.a.readyState!=WebSocket.OPEN?"Not Connected":"",t.j?"Info Share":""]];for(let [d,g,...h]of c)if(d){c=g;e="";let m;for(let T of h)T&&(e+=" ("+T+")");1==L.j&&(c+=e,e="");m=f.measureText(e).width;
$a(a-f.measureText(c).width-m,b-10,c,"hsl("+fa(bc*Ab+(b-j7)/zf)%360+", 100%, 50%)");$a(a-f.measureText(e).width,b-10,e,"#888");b-=20}},Kc=a=>{let b=rb.scrollTop===rb.scrollHeight-rb.clientHeight,c=[];for(let e of a)c.push(r("div",{color:e[0],whiteSpace:e[2]?"pre":"normal"},{innerText:e[1]}));rb.append(r("div",{[Vb]:nc,[x]:H,[He]:df},{},c));b&&rb.scroll({top:rb.scrollHeight,behavior:"instant"})},Lf=a=>{a=a.data.split(" ");switch(l(a.shift())){case 0:for(var b of a)b=l(b),la(t.l,b)||t.l.push(b);break;
case 1:a=jd(t.l,l(a[0]));t.l.length-1>a?t.l[a]=t.l.pop():t.l.pop();break;case 2:Kc([["#88f",a.shift().replace("_"," ")],["#fff",": ",1],["#fff",a.join(" ")]]);break;case 3:t.a.send("");t.j&&null!==c3&&t.a.readyState==WebSocket.OPEN&&(a=RD.pool[c3],t.a.send("1 "+[a.hp,a.hpMax,a.armorAmount,30*Af[c1.armor],a.currentBullets,a.maxBullets,rc[a.class],a.x,a.y,a.color.a,o3[1],o3[2],o3[3],c9.current/c9.total].join(" ")));break;case 4:t.i=a.join(" ");break;case 5:Kc([["#f88",a.join(" ")]]);break;case 6:b=
a[0].replace("_"," "),2>a.length?delete t.k[b]:(a[0]=b,t.k[b]=a)}},he=()=>t.a=Ob(new WebSocket("wss://cheats.gatsio.repl.co/"+sb(b4)+"/"+encodeURIComponent(o4.server+"/"+c22)+"/"+t.h),{onopen:a=>{db.hidden=!t.e;Kc([["#ff0","Connected"]])},onmessage:Lf,onerror:a=>t.i="Error",onclose:a=>{t.l=[];t.a=0;Kc([["#ff0","Disconnected"+(t.i?" ("+t.i+")":"")]])}}),Mf=(a,{style:b},c,e)=>{if(e)return Eb.focus();j47=c.value;j46&&""!=j47?(Fb(C.a,j47.replace(/,/g,"~").substring(0,30)),b[x]=$b,c.value=j47=""):j46&&
""==j47?b[x]=$b:j46||(b[x]=xf,c.focus());j46=!j46;J(C.a,7,j46*!L.h);a.send(a59("focus"))},ie=(a,b,c)=>{a=[l(a.slice(1,3),16),l(a.slice(3,5),16),l(a.slice(5,7),16)];b=[l(b.slice(1,3),16),l(b.slice(3,5),16),l(b.slice(5,7),16)];let e="#";for(let g=0;3>g;g++){var d=b[g];d=fa(d+c*(a[g]-d)).toString(16);e+=1==d.length?"0"+d:d}return e},Nf=(a,b)=>{var c=j11/2-a.x;a=j12/2-a.y;c=[[0,1][1<c],[3,2][1<a]][Sd(c)>Sd(a)];J(b,c,0);J(b,c,1)},je=a=>{if(!j43){var b=.01*(100/j11-j31),c=.01*(100/j12-j41),e=72-b,d=72-
b,g=c24/j11*144,h=c24/j12*144,m=.5*(144-g),T=.5*(144-h);f.globalAlpha=.5;f.fillStyle="#808080";f.fillRect(5,20,150,150);f.fillStyle="#7a7a7a";f.fillRect(8,23,144,144);f.fillStyle="#b5b5b5";f.strokeStyle="#d9d9d9";f.lineWidth=1;f.fillRect(e+8,d+23,2*b,2*c);if("FFA"==c22||"TDM"==c22)f.strokeStyle="#d9d9d9",j25(f,m+8,T+23,g,h);else if("2TEAM"==c22||"DOM"==c22)for(b=0;4>b;b++)f.strokeStyle=["#d9d9d9","#f26740","#8dd8f8"][j52[b+1]],e=c=52,b&1&&(c+=40-g),1<b&&(e+=40-h),j25(f,c+8,e+23,g,h);f.strokeStyle=
"#666";f.lineWidth=0;if(t.j)for(let A in t.k)A!=a.u&&(g=t.k[A],f.fillStyle=g[10],j22(f,g[8]/j11*144+8,g[9]/j12*144+23,2),f.fill());null!=a&&a!==K&&(f.fillStyle=a.color.a,j22(f,a.x/j11*144+8,a.y/j12*144+23,2),f.fill(),f.globalAlpha=1)}},ke=a=>{let b=a60("mouse-move",{mouseX:j16[0],mouseY:j16[1],mouseAngle:j16[2]});RF.list[a]!==K&&b!==j15&&RF.list[a].send(a66(j15=b))},le=(a,b)=>{var c=-b.x,e=-b.y,d=j11-b.x,g=j12-b.y,h=RD.pool[c3],m=c+j11/2-c24/2,T=e+j12/2-c24/2;b=[{x:c+j11/2-1E3,y:e+j12/2-1E3},{x:c+
j11/2+1E3-c24,y:e+j12/2-1E3},{x:c+j11/2-1E3,y:e+j12/2+1E3-c24},{x:c+j11/2+1E3-c24,y:e+j12/2+1E3-c24}];var A=(j11-c24)/2,za=(j12-c24)/2;h=h.x>A&&h.x<A+c24&&h.y>za&&h.y<za+c24?v.p:v.o;for(A=0;4>A;A++)b[A].z=[v.o,v.r,v.q][j52[A+1]];a.fillStyle=v.g[1];a.fillRect(0,0,j7,j8);if("FFA"==c22||"TDM"==c22)a.fillStyle=h[1],a.fillRect(m,T,c24,c24);if("2TEAM"==c22||"DOM"==c22)for(A=0;A<b.length;A++)a.fillStyle=b[A].z[1],a.fillRect(b[A].x,b[A].y,c24,c24);a.strokeStyle=v.g[0];for(A=0;A<=j12;A+=v.c)0<e+A&&e+A<=g&&
j21(a,c,e+A,d,e+A,v.d);for(A=0;A<=j11;A+=v.b)0<c+A&&c+A<=d&&j21(a,c+A,e,c+A,g,v.e);a.strokeStyle="#aaa";a.lineWidth=10;a.strokeRect(c,e,j11,j12);a.lineWidth=v.s;if("FFA"==c22||"TDM"==c22)a.strokeStyle=h[0],a.strokeRect(m,T,c24,c24);if("2TEAM"==c22||"DOM"==c22)for(c=0;c<b.length;c++)a.strokeStyle=b[c].z[0],a.strokeRect(b[c].x,b[c].y,c24,c24)},me=(a,b)=>{b.current=b.new;if(!(1>j3||2.6<j3)){var c=.03,e=1.695*j1;a.fillStyle="#609b68";a.textAlign=D;a.font="bold 11px Arial";a.fillText("Total Players Online: "+
c29,1.845*j1,.032*j2);a.fillStyle="#4C4C4C";0<b.current.length&&a.fillText("Leaderboard",1.845*j1,.07*j2);a.textAlign="start";for(let h of b.current){if(!h.userId)continue;b=1.695*j1;var d=h.userId,g=Zd(sb(d));let m=-1599485949==g?"#00f":la(t.l,g)?"#88f":la(cb,d)?"#f00":la(bb,d)?"#000":0;g={"#00f":"DEV","#88f":"THnet","#f00":"Target","#000":"Friend"}[m];a.globalAlpha=.5;a.fillStyle=["#808080","#f26740","#40b2e5"][l(h.teamCode)];a.fillRect(1.7*j1,(.05+c)*j2,.295*j1,.04*j2);h.isMember&&(a.globalAlpha=
.65,drawImage(j30.vip,1.703*j1,(.055+c)*j2,18,10));a.globalAlpha=1;a.fillStyle="white";a.font="10px Arial";a.fillText(d+": "+h.score,(h.isMember?1.735:1.705)*j1,(.0787+c)*j2);a.textAlign="right";a.fillText("Kills: "+h.kills,1.99*j1,(.0795+c)*j2);a.textAlign="start";L.p&&m&&(a.strokeStyle=a.fillStyle=m,a.font="bold 13px consolas",d=a.measureText(g).width+8,a.globalAlpha=.5,a.fillRect(b-d,(.05+c)*j2,d,.04*j2),a.globalAlpha=a.lineWidth=1,a.strokeRect(b-d,(.05+c)*j2,d,.04*j2),a.fillStyle="#ffffff",a.fillText(g,
b-d+4,(.0795+c)*j2),b-=d);e=hb(e,b);c+=.045}a.textAlign="right";a.fillStyle="#4C4C4C";a.font="bold 11px Arial";a.fillText("Players in arena: "+o4.currentPlayers,1.99*j1,(c+.075)*j2);a.textAlign="start";return e}},Qb=(a,b,c)=>{let e=RD.pool[c3];var d=(e.x-c2.x)*(b?1:j6)-a.clientX;b=(e.y-c2.y)*(b?1:j5)-a.clientY;let g=ab(b,d)/ia+180;c=g+(c?0:$c(18/Ea(d**2+b**2))/ia);j16=[fa(d),fa(b),fa(g)];c||0===c||(c=g);e.playerAngle=fa(c);j9=[a.clientX,a.clientY];q.n&&(d+=a.clientX-V.x,b+=a.clientY-V.y,g=ab(b,d)/
ia+180);e.mouseAngle=fa(g);j39=Ea(d**2+b**2)},ne=(a,b)=>{if(b.data!==K&&RF.list[0]!==K){b=a67(b.data);"."==b&&(RF.list[a].a74(),RF.list[a].a76());for(var c=b.split("|"),e=0;e<c.length;e++){var d=a61(c[e]);if(d)switch(d.code){case "a":a78();a90();c3=d.id;c2=new RE(d.c2);c2.trackingId=d.id;a1(c2);RD.pool[d.id].activate(d,0);c10=0;c5=d.hp;c6=d.armorAmount;c4=1;var g=RD.pool[c3];g&&(c2.x=g.x-window.innerWidth/j6/2,c2.y=g.y-window.innerHeight/j5/2);b4=d.username;b38=d.b38;selfPremiumMember=d.isPremiumMember;
j43=b11=0;t.b&&!t.a&&he();break;case "b":RD.pool[d.id].applyPrimaryUpdate(d);break;case "c":RD.pool[d.id].applyAuxUpdate(d);break;case "d":RD.pool[d.id].activate(d,1);break;case "e":RD.pool[d.id].deactivate();break;case "f":c3&&RD.pool[c3].applyFirstPersonUpdateData(d);break;case "g":RC.pool[d.id].activate(d);break;case "h":(g=RC.pool[d.id])&&g.applyUpdate(d);break;case "i":RC.pool[d.id].deactivate();break;case "j":RB.pool[d.id].activate(d);break;case "k":RB.pool[d.id].applyUpdate(d);break;case "l":RB.pool[d.id].deactivate();
break;case "m":RA.pool[d.id].activate(d);break;case "n":(g=RA.pool[d.id])&&g.applyUpdate(d);break;case "o":RA.pool[d.id].deactivate();break;case "p":c10=d.level;break;case "q":j27.push({x:d.x/10,y:d.y/10,c42:0});break;case "r":g=l(d.type);let m=d.content;1==g&&W.c&&Fb(a,W.d.replace("[[ENEMY]]",sb(m.replace("Guest ",""))));(2==g||9==g)&&W.e&&Fb(a,W.f.replace("[[ENEMY]]",sb(m.replace("Guest ",""))));5==g&&Nf(a,RD.pool[c3]);if(3==l(d.type)){d=_.find(o10,{type:3});m=l(m);if(!d){o10.push({type:g,content:m,
initTime:Date.now()});break}d.content+=m;d.initTime=Date.now();break}o10.push({type:g,content:m,initTime:Date.now()});break;case "s":a4();break;case "t":b11=1;a45();break;case "v":j38.new=d.j38;o4.currentPlayers=d.currentPlayers;break;case "w":b4=d.username;b38=d.b38;selfPremiumMember=d.isPremiumMember;b3=1;a111("registerModal");a111("loginModal");0<d.rememberCookie.length&&a2("remember_cookie",d.rememberCookie,365);selfPremiumMember&&$("#hostServerTabLi").show();b2=0;a104();a99();b24();break;case "x":a18(d);
b2=0;a99();break;case "y":a20(d);break;case "z":d.status&&(b4="Mystery Creature",b38="",b3=selfPremiumMember=0,$("#hostServerTabLi").hide());a99();a104();break;case "sq":j52[1]=l(d.squareOneTeam);j52[2]=l(d.squareTwoTeam);j52[3]=l(d.squareThreeTeam);j52[4]=l(d.squareFourTeam);break;case "sz":j31=l(d.newSize);j41=l(d.newSize);break;case "sta":c27=d;break;case "re":j43=1;a80("respawn");break;case "fr":j43=1;a80("respawn");grecaptcha.execute("6LenZt4ZAAAAAF-2nPKzH9111gkjBlaJCEp8UsQV",{action:"connect"}).then(function(T){grecaptcha.LoToken=
T;grecaptcha.LoTime=(new Date).getTime();RF.list[a].send(new Uint8Array(a68("q,"+grecaptcha.LoToken+","+grecaptcha.LoTime)))});break;case "reco":b2=b1=0,servers=[],c4=b11=0,a47()}}if("+"==b)RF.list[a].b12=1,RF.list[a].send(new Uint8Array(a68("q,"+grecaptcha.LoToken+","+grecaptcha.LoTime))),b17(),a91(),b15=0,b1||(loginViaCookie(),b1=1);else if("version"==b.substring(0,7)){var h=b35(b.substr(8));b=b35(window.clientVersion);b35(window.latestVersion);if(h.pat>b.pat||h.min!=b.min||h.maj!=b.maj)return b36(h);
a2("clv",b.maj+"."+b.min+"."+b.pat);b37()}else if("highScores"==b.substring(0,10)&&20<b.substr(11).length)for(h in b=JSON.parse(b.substr(11)),Za("hscrs").style[x]="block",Za("highScoresHeading").innerHTML="Top Scores Today",c=Za("hsd"),c.innerHTML="",b)b[h].score&&(e=document.createElement("div"),e.className="high-score-row",d=document.createElement("div"),d.className="vip-image-div",b[h].is_member&&(g=document.createElement("img"),g.src="/img/vip.png",g.className="vip-score-image",d.appendChild(g)),
e.appendChild(d),d=document.createElement("div"),d.className="high-scores-text",d.innerHTML=b[h].username+": "+b[h].score.toLocaleString(),e.appendChild(d),c.appendChild(e));else"c22"==b.substring(0,8)&&a103(a61(b).j50)}},Hc=[[sa[0],a=>{for(let b in Hc)if(l(b)){let c=r("div",{[w]:Q,[wa]:I,[ca]:D,[Ka]:ea,[N]:D,[P]:Xb,[y]:Hc.length-1==b?kf:Ma},{innerText:Ga(Hc[b][0]),onmouseover:()=>c.style[P]=Bd,onmouseout:()=>c.style[P]=Xb,onclick:()=>Pb(l(b))});a(c)}}],[sa[1],a=>{for(let b in Zc)for(let c in Zc[b]){let e=
0==c;a(r("div",{[Ub]:e?Wa:c&1?Fd:pc,[Tb]:e&&1*b?Lb:"",[Ta]:e?fb:"",[Vb]:I,[Fe]:e?fb:c&1?Ed:I},{innerText:Zc[b][c]}))}}],[sa[2],a=>{a(r("div",{},{innerText:"Coming Soon"}))}],[sa[3],a=>{let b={p:"abj",q:"dfx",r:"ck",s:"hiw",t:"nelovy",u:"gm"};for(let c in b){let e=[];for(let d of b[c])e.push("k"==d?Aa(wc[d],g=>n[d]=ka(0,n[d]+50*g,500),()=>n[d]):"x"==d?Aa(wc[d],g=>n[d]=ka(0,n[d]+g,4),()=>n[d]+1):ta(wc[d],()=>n[d]=1-n[d],()=>n[d]));a(tb(wc[c],e))}}],[sa[4],a=>{let b={p:"abnu",q:"cdefg",r:"jklmto",s:"hi"};
for(let c in b){let e=[];for(let d of b[c])e.push("a"==d?Gc(xc[d],Ac[0],g=>q[d]=g,()=>q[d]):"u"==d?Aa(xc[d],g=>q[d]=ka(1,q[d]+.01*g,2),()=>fa(100*(q[d]-1))):ta(xc[d],()=>q[d]=1-q[d],()=>q[d]));a(tb(xc[c],e))}}],[sa[5],a=>{for(let h in W)if("b"!==h)if(la("dfh",h)){let m=r("input",{[La]:qa,[w]:Q,[y]:mb,[U]:Ca,[x]:H,[xa]:Da,[ca]:D,[va]:I,[N]:D,[P]:xb},{type:nb,maxlength:"h"===h?32:38,onfocus:()=>Pa=1,onblur:()=>Pa=0,oninput:()=>{W[h]=m.value;Fa()},value:W[h]});a(r("div",{[w]:Q,[x]:H,[wa]:I,[Ta]:da,[Ka]:Zb,
[Va]:da,[N]:Na,[y]:Ma},{title:cd[h][1]},[m]))}else a(ta(cd[h],()=>W[h]=1-W[h],()=>W[h]));let b=r("input",{[La]:qa,[w]:Q,[y]:mb,[U]:Ca,[x]:H,[xa]:Da,[ca]:D,[va]:I,[N]:D,[P]:xb},{type:nb,maxlength:32,onfocus:()=>Pa=1,onblur:()=>Pa=0,oninput:()=>{g&&!(W.b[g]=b.value)&&delete W.b[g]},value:""}),c=r("div",{[w]:Q,[x]:H,[wa]:I,[Ta]:yb,[Ka]:Zb,[Va]:da,[P]:Xb,[N]:Na,[y]:Ma},{title:Ga(cd[0])},[b]),e=r("div",{[w]:Q,[x]:Od,[wd]:Ye}),d,g=0;for(let h of[0,48,49,50,51,52,53,54,55,56,57,66,67,69,70,71,72,73,74,75,
76,77,79,80,81,85,86,88,89,90]){let m=r("div",{[x]:H,[y]:e.width/9,[ca]:D,[N]:D,[P]:Pe},{innerText:h?" "+String.fromCharCode(96<=h&&105>=h?h-48:h):" ",onclick:()=>{let T=d;d=m;g=h;T.G();m.G();b.value=W.b[h]||""},G:()=>Ua(m,{[U]:yb+gb+(d===m?Cd:qa)})});h||(d=m);m.G();e.append(m)}a(e);a(c)}],[sa[6],a=>{let b={k:"aeghi",l:"bco",m:"djp",n:"f"};for(let c in b){let e=[];for(let d of b[c])e.push("j"==d?Gc(dd[d],Ac[2],g=>L[d]=g,()=>L[d]):ta(dd[d],()=>L[d]=1-L[d],()=>L[d]));a(tb(dd[c],e))}}],[sa[7],a=>{let b=
[bb,cb,Bc][cc],c=cc?bb:cb;var e=r("div",{[w]:mf,[y]:mb,[La]:Yb,[U]:Ca,[x]:H,[xa]:Da,[ca]:D,[N]:D,[P]:Qe},{innerText:"Add",onclick:()=>{var h=sb(d.value);la(b,h)||(2!==cc&&la(c,h)&&Hb(c,h),Hb(b,h),h=Pb(6),Fa(od(h)))}});let d=r("input",{[w]:af,[y]:mb,[La]:qa,[U]:Ca,[x]:H,[Sc]:I,[xa]:Da,[ca]:D,[N]:D,[P]:xb},{type:nb,onfocus:()=>Pa=1,onblur:()=>Pa=0,oninput:()=>d.value=d.value.replace(/[^0-9a-zA-Z ]/g,"").slice(0,12),value:""});e=r("div",{[w]:Q,[x]:H,[wa]:I,[Ta]:yb,[Ka]:Zb,[Va]:da,[P]:Xb,[N]:Na,[y]:Ma},
{title:zc[3][cc]},[e,d]);var g=[];for(let h=0;3>h;h++)g[h]=r("div",{[w]:cf,[wa]:I,[ca]:D,[Ka]:Zb,[De]:h==zc.length-1?"":Zb,[Va]:da,[Ta]:da,[N]:D,[P]:Xb,[x]:H,[xa]:Da,[y]:Ma},{innerText:Ga(zc[h][0]),title:Ga(zc[h][1]),onclick:()=>{cc=h;return Pb(6)}});a(r("div",{},{},[r("div",{[w]:Q,[x]:H},{},g),e]));for(let h of b)e=r("div",{[mc]:nb},{innerText:h}),g=r("div",{[w]:Wa,[y]:Wa,[U]:Ca,[x]:H,[xa]:Da,[ca]:D,[N]:D,[P]:Vc},{innerText:"X",onclick:()=>{Hb(b,h);return Pb(6)}}),e=r("div",{[w]:Q,[x]:H,[wa]:I,[Ka]:ea,
[Va]:da,[N]:Na,[y]:Ma},{},[e,g]),a(e)}],[sa[8],a=>{a(ta(Xd[0],()=>ja[0]=1-ja[0],()=>ja[0]));let b=[],c=r("div",{[w]:" 100%",[x]:Od,[wd]:Ze});for(let e=1;4>e;e++){let d=r("div"),g=r("div",{[w]:Wa,[y]:Wa,[U]:ea,[wa]:da,[Je]:da,[P]:Le}),h=r("div",{[w]:Q,[wa]:I,[x]:H,[Ka]:ea,[Va]:da,[N]:Na,[y]:Ma},{onclick:()=>{c.p(gd=e);for(let m of b)m.f()}},[d,g]);h.b=(m,T)=>{d.innerText=Df[m]||Ga(Xd[1]);nd(g);if(m&&j30[m]){T=g;var A=T.append;m=j30[m];let za=r("canvas",{[w]:Q,[y]:Q},{[w]:m.width,[y]:m.height});za.getContext("2d").drawImage(m,
0,0,m.width,m.height);A.call(T,za)}};h.b(ja[e],1);h.f=()=>h.style[P]=e==gd?Bd:Xe;h.f();b.push(h)}c.p=e=>{nd(c);var d=2===e?Mb:id;let g=4-e;for(let h of d)d=r("div",{[U]:yb+gb+(ja[e]===h?Cd:qa),[y]:c.width/4},{onclick:()=>{b[e-1].b(ja[e]=ja[e]===h?"":h);2!==g&&ja[e]&&ja[g]===ja[e]&&b[g-1].b(ja[g]="");c.p(e);Fa()}},[j30[h]]),c.append(d)};c.p(gd);for(let e of b)a(e);a(c)}],[sa[9],a=>{a(ta(yc[0],()=>{u.g?(clearTimeout(u.g),u.g=0,Fb(C.a," ")):be(C.a)},()=>u.g));let b=(d,g)=>d.replace(/\n/g,"").slice(0,
g),c=()=>{u.b=ka(5,u.b,30);u.d=ka(-5,u.d,5);u.c=ka(25,u.c,1E3);u.e=b(u.e,5);u.a=b(u.a,99999);u.h=ka(500,u.h,1E4);u.j=b(u.j,25-u.k.length);u.k=b(u.k,25-u.j.length);Fa()};c();for(let d of"bdch")a(Aa(yc[d],g=>c(u[d]+=("h"==d?500:"c"==d?25:1)*g),()=>u[d]/("h"==d?1E3:1)));for(let d of"eajk"){var e=r("div",{[lc]:nc,[Tc]:gf,[x]:H},{innerText:yc[d][0]});let g=r("input",{[w]:"a"==d?bf:nf,[y]:mb,[La]:qa,[U]:Ca,[x]:H,[xa]:Da,[ca]:D,[N]:D,[P]:xb},{type:nb,oninput:()=>{u[d]=g.value;c();g.value=u[d]},onfocus:()=>
Pa=1,onblur:()=>Pa=0,value:u[d]});e=r("div",{[w]:Q,[x]:H,[wa]:I,[Ta]:yb,[Ka]:ea,[Va]:da,[N]:Na,[y]:Ma},{title:yc[d][1]},[e,g]);a(e)}}],[sa[10],a=>{for(let b of"abcj")a(ta(Yd[b],()=>B[b]=1-B[b],()=>B[b]));for(let b of"defg")a(Aa(Yd[b],c=>{B[b]+=(la("de",b)?5:1)*c;B.d=(360+B.d)%360;B.e=(365+B.e)%365;B.f=ka(-180,B.f,180);B.g=ka(1,B.g,62)},()=>B[b]));md=(b,c,e,d)=>{if(!qb.hidden){e=(B.d+bc*B.f)*ia;d=e+B.e*ia;var g=1.5*b.F+20;Gb(b,{x:g*ha(e),y:g*ma(e)},c,2,"#f00");Gb(b,{x:g*ha(d),y:g*ma(d)},c,2,"#00f");
f.lineWidth=1;f.beginPath();f.arc(b.x+c.x,b.y+c.y,g,-e+Oa/4,-d+Oa/4,!0);f.stroke()}}}],[sa[11],a=>{a(tb(Xa[0],[ta(Xa.a,()=>p.a=1-p.a,()=>p.a),Aa(Xa.b,b=>p.b=ka(20,p.b+10*b,300),()=>p.b)]));a(tb(Xa[1],[ta(Xa.d,()=>p.d=1-p.d,()=>p.d),Aa(Xa.e,b=>p.e=ka(0,p.e+b,50),()=>p.e),Aa(Xa.i,b=>p.i=ka(0,p.i+b,10),()=>p.i),ta(Xa.g,()=>p.g=1-p.g,()=>p.g),Gc(Xa.l,Ac[3],b=>p.l=b,()=>p.l)]));a(tb(Xa[2],[ta(Xa.h,()=>p.h=1-p.h,()=>p.h)]))}],[sa[12],a=>{let b={a:"bcdeg",n:"opqrs",h:"mijklt"};for(let c in b){let e=[];for(let d of b[c]){let g;
switch(d){case "m":g=Gc(Ya.m,Ac[1],h=>v.m=h,()=>v.m);break;case "s":g=Aa(Ya.s,h=>v.s=ka(0,v.s+h,20),()=>v.s);break;case "d":g=Aa(Ya.d,h=>v.d=ka(0,v.d+h,10),()=>v.d);break;case "e":g=Aa(Ya.e,h=>v.e=ka(0,v.e+h,10),()=>v.e);break;case "b":g=Aa(Ya.b,h=>v.b=ka(2,v.b+h,500),()=>v.b);break;case "c":g=Aa(Ya.c,h=>v.c=ka(2,v.c+h,500),()=>v.c);break;default:g=If(Ya[d],v[d])}e.push(g)}a(tb(Ya[c],e))}a(pd(Ya[0],()=>"yes"==prompt(Ya[0],Ya[1])&&Fa(v={b:20,c:20,d:1,e:1,g:["#e3e3e8","#efeff5"],o:["#aaaaaa","#f9f9f9"],
p:["#00cc66","#f9f9f9"],q:["#8dd8f8","#f9f9f9"],r:["#f26740","#f9f9f9"],s:4,m:2,i:["#808080","#dfbf9f"],j:["#808080","#bec8dd"],k:["#808080","#53c68c"],l:["#2e2d2d","#f0ba37"]})))}],[sa[13],a=>{a(r("div",{},{innerText:"Coming Soon"}))}],[sa[15],a=>{a(ta(Cb.b,()=>{t.b=!t.b;null!==c3&&(t.b?he():t.a&&(t.i="Manual",t.a.close()))},()=>t.b));a(ta(Cb.j,()=>(t.j=1-t.j)||t.a.send("1"),()=>t.j));a(ta(Cb.e,()=>t.e=1-(db.hidden=1-db.hidden),()=>t.e));let b=[];for(let c=0;c<Cb[1].length;c++)b[c]=r("div",{[Ta]:I},
{innerText:Cb[1][c]});a(tb(Cb[0],b))}],[sa[16],a=>{for(let b in dc)a(ta(Cf[b],()=>dc[b]=1-dc[b],()=>dc[b]))}],[sa[17],a=>{for(let b in E){let c;switch(b){case "c":c=ta(Bb[b],()=>E[b]=2.5===E[b]?1:2.5,()=>1===E[b]);break;case "d":c=ta(Bb[b],()=>E[b]=1-E[b],()=>E[b]);break;case "a":c=Aa(Bb[b],e=>E[b]=ka(1,E[b]+e,50),()=>E[b]);break;case "e":c=Aa(Bb[b],e=>E[b]=ka(1,E[b]+e,100),()=>E[b]);break;case "b":c=Aa(Bb[b],e=>E[b]=parseFloat(ka(.5,E[b]+.05*e,2.5).toFixed(2)),()=>E[b])}a(c)}a(pd(Bb[0],()=>{for(let b of RF.list)b.socket.close()}));
a(pd(Bb[1],()=>localStorage.removeItem("TioHax_bootloader")));a(Hf(Cb.h,b=>t.h=b,()=>t.h))}],[sa[18],a=>{for(let b of yf)for(let c in b){let e=0==c;a(r("div",{[Ub]:e?Wa:c&1?Fd:pc,[Tb]:e?Lb:"",[lc]:e?fb:c&1?Ed:I,[Ta]:e?fb:"",[Vb]:I},{innerText:b[c]}))}}]];setInterval(console.dir,3E4,"GATS.io TioHax Menu\nMade by Taureon.\nhttps://cheats.gatsio.repl.co/\nhttps://discord.gg/CwWd5UKf6R");RE=function(a){let b=this;for(let c of"x y spdX spdY width height".split(" "))b[c]=l(a[c]),isNaN(b[c])&&(b[c]=0);b.update=
b.G=function(c){let e=RD.pool[b.trackingId];e&&(e.mouseAngle===K&&(e.mouseAngle=0),q.b?(b.x=e.x+fa(e.spdX/E.c)-j40.x,b.y=e.y+fa(e.spdY/E.c)-j40.y):(c||(b.spdX+=qc(e.spdX-b.spdX)/10,b.spdY+=qc(e.spdY-b.spdY)/10,-.1<b.spdX&&.1>b.spdX&&(b.spdX=0),-.1<b.spdY&&.1>b.spdY&&(b.spdY=0),b.spdX=fa(10*b.spdX)/10,b.spdY=fa(10*b.spdY)/10),c=e.mouseAngle*ia,-22<b.spdX&&22>b.spdX&&(b.x=j39/15*ma(c)+(e.x-j40.x)-12*b.spdX),-22<b.spdY&&22>b.spdY&&(b.y=j39/15*ha(c)+(e.y-j40.y)-12*b.spdY)))};b.getRelPos=c=>({x:c.x-b.x,
y:c.y-b.y});b.getPos=()=>({x:b.x,y:b.y});b.getSize=()=>({width:b.width,height:b.height})};RB.prototype.I=function(){var a=this.x-c2.x,b=this.y-c2.y;f.beginPath();f.moveTo(this.f[0][0]+a,this.f[0][1]+b);for(let c=1;4>c;c++)f.lineTo(this.f[c][0]+a,this.f[c][1]+b);f.closePath();f.fill()};RB.prototype.J=function(){var a=-(this.angle*ia-Rd/2);let b={x:this.i*ha(a),y:this.i*ma(a)};a=[ab(this.k,this.l)+a,ab(0-this.k,this.l)+a,ab(0-this.k,0-this.l)+a,ab(this.k,0-this.l)+a];let c=Ea(this.k**2+this.l**2);for(let e=
0;4>e;e++)a[e]={x:b.x+c*ha(a[e]),y:b.y+c*ma(a[e])};this.f=[[a[0].x,a[0].y,a[1].x,a[1].y],[a[1].x,a[1].y,a[2].x,a[2].y],[a[2].x,a[2].y,a[3].x,a[3].y],[a[3].x,a[3].y,a[0].x,a[0].y]];this.g=b;this.h=c};RB.prototype.activate=function(a){this.parent=a.parentId;this.type=a.type;this.x=a.x/10;this.y=a.y/10;this.angle=a.angle;this.maxHp=a.maxHp;this.hp=a.hp;this.isPremium=a.isPremium;this.model=a11(this.type,this.isPremium);this.j=this.i=this.l=this.k=0;switch(this.type){case "crate":this.l=this.k=45;this.j=
1;break;case "longCrate":this.k=45;this.l=20;this.j=1;break;case "userCrate":case "premiumCrate":this.l=this.k=15;this.j=1;break;case "shield":this.k=30,this.l=10,this.i=33,this.j=1}this.activated=1;this.J()};RB.prototype.G=function(){this.model&&(this.animationFrame=(this.animationFrame+1)%this.model.length);if("shield"==this.type){var a=RD.pool[this.parent];if(a){var b=a.playerAngle*ia;this.x=a.x+a.spdX/E.c+ma(b);this.y=a.y+a.spdY/E.c+ha(b);this.angle=a.playerAngle}}};RB.prototype.applyUpdate=function(a){let b=
this.angle!=a.angle;this.x=a.x/10;this.y=a.y/10;this.angle=a.angle;a.hp!==K&&""!=a.hp&&(this.hp=l(a.hp));b&&this.J()};RB.prototype.K=function(){if(this.model){var a=this.maxHp?this.hp/this.maxHp:1,b=this.model[this.animationFrame],c={crate:v.i,longCrate:v.j,userCrate:this.isPremium?v.l:v.k}[this.type];if(c){b[0][1][3]=c[0];b[1][1][3]=c[1];if(0>a||1<a)a=0;L.g||(a=zb(5*a)/5);v.m&1&&(b[0][1][3]=ie(c[0],v.t[0],a));v.m>>1&&(b[1][1][3]=ie(c[1],v.t[1],a))}a38(f,c2,this,this.angle,b)}};RC.prototype.G=function(){this.model&&
(this.animationFrame=(this.animationFrame+1)%this.model.length);this.x+=this.spdX;this.y+=this.spdY};RC.prototype.K=function(){if(this.isKnife)return a38(f,c2,this,this.angle,this.model[this.animationFrame]);f.strokeStyle="#000";this.silenced&&!q.h?f.strokeStyle="#D3D3DA":this.ownerId==c3||0<this.teamCode&&this.teamCode==RD.pool[c3].teamCode?f.strokeStyle="#107a24":RD.pool[c3].thermal&&(f.strokeStyle="#f00");let a=this.x-c2.x,b=this.y-c2.y;j21(f,a,b,a+this.length*ma(this.angle*ia),b+this.length*ha(this.angle*
ia),this.width)};RD.prototype.activate=async function(a,b){this.color=a.color;this.x=parseFloat(a.x/10);this.y=parseFloat(a.y/10);this.z=this.A=this.spdY=this.spdX=this.b=this.c=this.d=this.e=0;this.F=l(a.radius/10);this.playerAngle=l(a.playerAngle);this.hp=l(a.hp);this.H=this.hp*this.F/100;this.armorAmount=l(a.armorAmount);this.shootingAnimation=a6("shooting",this.class=a.class);this.ghillie=a.ghillie;this.maxBullets=a.maxBullets;this.invincible=a.invincible;this.isLeader=l(a.isLeader);this.isPremiumMember=
l(a.isPremiumMember);this.teamCode=l(a.teamCode);this.chatBoxOpen=l(a.chatBoxOpen);this.activated=1;b||(this.currentBullets=l(a.currentBullets),this.maxBullets=l(a.maxBullets),this.armor=a.armor,this.c2=a.c2,this.hpMax=a.hpMax,this.numExplosivesLeft=3,j31=l(a.mapWidth)/10,j41=l(a.mapHeight)/10);fe(this,formatUserName(a.username))};RD.prototype.applyFirstPersonUpdateData=function(a){a.currentBullets!==K&&""!=a.currentBullets&&(this.currentBullets=l(a.currentBullets));a.score!==K&&""!=a.score&&(this.score=
l(a.score));a.kills!==K&&""!=a.kills&&(this.kills=l(a.kills));a.rechargeTimer!==K&&(c9={current:l(a.rechargeTimer)*E.c,total:l(a.rechargeTimer)*E.c});a.maxBullets!==K&&""!=a.maxBullets&&(this.maxBullets=l(a.maxBullets));if(a.c2!==K&&""!=a.c2){let b=a.c2.split("x");c2.width=l(b[0]);c2.height=l(b[1])}a.thermal!==K&&""!=a.thermal&&(this.thermal=l(a.thermal));a.numExplosivesLeft!==K&&""!=a.numExplosivesLeft&&(this.numExplosivesLeft=l(a.numExplosivesLeft))};RD.prototype.G=function(){let a=fa(this.hp/100*
(this.F-this.armorAmount/10-1));L.e?this.H=a:(this.H>a-.5&&this.H<a+.5?this.H=a:this.H>a?this.H-=.5:this.H<a&&(this.H+=.5),0>this.H&&(this.H=0));0<this.hp&&(this.x+=fa(this.spdX/E.c),this.y+=fa(this.spdY/E.c));0<this.j47Timer&&(this.j47Timer-=2.5/E.c,0>=this.j47Timer&&(this.j47=""));this.shootingAnimation=a6("shooting",this.class);this.shooting?this.shootingFrame=(this.shootingFrame+1)%this.shootingAnimation.length:this.reloading&&this.reloadingAnimation&&(this.reloadingFrame=(this.reloadingFrame+
1)%this.reloadingAnimation.length);this.shooting||(this.shootingFrame=0);this.reloading||(this.reloadingFrame=0)};RD.prototype.applyPrimaryUpdate=function(a){this.x=parseFloat(a.x/10);this.y=parseFloat(a.y/10);let b=parseFloat(a.spdX/10),c=parseFloat(a.spdY/10);this.b=this.d;this.c=this.e;this.d=b-this.spdX;this.e=c-this.spdY;this.z=this.spdX;this.A=this.spdY;this.spdX=b;this.spdY=c;n.b?(this.B=(b+this.z)/2,this.C=(c+this.A)/2,this.v=(this.d+this.b)/2,this.w=(this.e+this.c)/2):(this.B=b,this.C=c,
this.v=this.d,this.w=this.e);a.id!=c3&&(this.playerAngle=l(a.playerAngle))};RD.prototype.applyAuxUpdate=function(a){if(this.activated){a.color!==K&&""!=a.color&&(this.color=a.color);a.radius!==K&&""!=a.radius&&(this.F=l(a.radius/10));a.dashing!==K&&""!=a.dashing&&(this.dashing=l(a.dashing));a.ghillie!==K&&""!=a.ghillie&&(this.ghillie=l(a.ghillie));a.shooting!==K&&""!=a.shooting&&(this.shooting=l(a.shooting));a.isLeader!==K&&""!=a.isLeader&&(this.isLeader=l(a.isLeader));a.reloading!==K&&""!=a.reloading&&
(this.reloading=l(a.reloading));a.maxBullets!==K&&""!=a.maxBullets&&(this.maxBullets=l(a.maxBullets));a.invincible!==K&&""!=a.invincible&&(this.invincible=l(a.invincible));a.armorAmount!==K&&""!=a.armorAmount&&(this.armorAmount=l(a.armorAmount));a.chatBoxOpen!==K&&""!=a.chatBoxOpen&&(this.chatBoxOpen=l(a.chatBoxOpen));a.currentBullets!==K&&""!=a.currentBullets&&(this.currentBullets=l(a.currentBullets));if(a.hp!==K&&""!=a.hp){let b=l(a.hp);this.hp+1<b&&W.g&&void 0==c3&&Fb(this.id,W.h);this.hp=b}a.beingHit!==
K&&""!=a.beingHit&&(a.id==c3&&(j37=6),this.beingHit=l(a.beingHit));a.j47!==K&&""!=a.j47&&(this.j47=a.j47.replace(/~/g,","),this.j47Timer=200)}};RD.prototype.L=function(){var a=this.x-c2.x,b=this.y-c2.y;if(!this.ghillie||q.h||0!=this.spdX||0!=this.spdY||this.beingHit||this.shooting){this.isLeader&&(f.globalAlpha=.3,f.strokeStyle=this.color.a,f.lineWidth=10,j22(f,a,b,1.65*this.F));f.globalAlpha=this.invincible?.3:1;f.lineWidth=2;f.strokeStyle=f.fillStyle=this.isPremiumMember?"#000":"#666";j22(f,a,b,
this.F+1);f.fill();f.lineWidth=1;f.strokeStyle=f.fillStyle=this.color.b;j22(f,a,b,this.F-this.armorAmount/10);f.fill();this.dashing&&(f.strokeStyle="#bababa",j21(f,a,b,a-5*this.spdX,b-5*this.spdY,1),j21(f,a,b+20,a-5*this.spdX,b+20-5*this.spdY,1),j21(f,a,b-20,a-5*this.spdX,b-20-5*this.spdY,1),j21(f,a+20,b,a+20-5*this.spdX,b-5*this.spdY,1),j21(f,a-20,b,a-20-5*this.spdX,b-5*this.spdY,1));f.lineWidth=1;f.strokeStyle=f.fillStyle=this.color.a;j22(f,a,b,this.H+1);f.fill();if(c37&&this.id!=c3){f.fillStyle=
this.isPremiumMember?"#000":"#666";f.font="bold 12px Arial";f.textAlign="center";var c=L.i?this.s:this.t,e=f.measureText(c).width;this.isPremiumMember?(f.globalAlpha=.75,f.fillText(c,a-9,b+1.75*this.F),drawImage(j30.vip,a+e/2-6,b+1.75*this.F-9,18,10),f.globalAlpha=1):f.fillText(c,a,b+1.75*this.F);f.textAlign="start"}f.globalAlpha=1}else this.id!=c3&&1==RD.pool[c3].thermal?0<this.teamCode&&this.teamCode==RD.pool[c3].teamCode?(f.strokeStyle="#107a24",f.font="bold 12px Arial",f.textAlign="center",f.fillStyle=
"#107a24",f.fillText(this.t,a,b+1.75*this.F),f.textAlign="start"):f.strokeStyle="#f00":(f.strokeStyle="#efeff5",f.lineWidth=2,j22(f,a,b,this.F),f.fillStyle="#efeff5",f.fill());c37&&!la(Bc,this.u)&&(c=this.j47,""==c&&this.chatBoxOpen&&(c="...")," "==c[c.length-1]&&(c=c.substring(0,c.length-1)),c.length&&(f.font="bold 12px Arial",f.textAlign="center",e=f.measureText(c).width,f.globalAlpha=.7,f.fillStyle=this.isPremiumMember?"#000":"#7a7a7a",f.fillRect(a-e/2-3,b+2.7*this.F-13,e+6,18),f.globalAlpha=1,
f.fillStyle=this.isPremiumMember?"#deb34c":"#fff",f.fillText(c,a,b+2.7*this.F),f.textAlign="start"))};RD.prototype.M=function(){if(!this.ghillie||this.spdX||this.spdY||this.beingHit||this.shooting){this.shootingAnimation=a6("shooting",this.class);var a=this.shootingAnimation[this.shootingFrame],b=0;this.beingHit&&(b=-1,this.beingHit=0);this.reloading&&(this.reloadingAnimation=a6("reloading",this.class,this.maxBullets-this.currentBullets,!this.currentBullets),a=this.reloadingAnimation[this.reloadingFrame]);
this.invincible&&(f.globalAlpha=.3);a38(f,c2,this.getAttr(),this.playerAngle,a,4,null,b);f.globalAlpha=1}else RD.pool[c3].thermal&&c3!=this.id&&(a=this.x-c2.x,b=this.y-c2.y,f.strokeStyle=0<this.teamCode&&this.teamCode==RD.pool[c3].teamCode?"#107a24":"#ff0000",j21(f,a,b,a+20*ma(this.playerAngle*ia),b+20*ha(this.playerAngle*ia),4))};RF.prototype.a74=function(){this.pingReceivedTime=Date.now();this.currentPing=this.pingReceivedTime-this.pingSentTime>>1;++this.numSuccessfulPings;this.m||(this.m=[]);this.m.push(this.currentPing);
this.m.length>E.a&&this.m.shift();this.n=0;for(let a of this.m)this.n+=a;this.n/=this.m.length;this.o=hb(...this.m);this.p=ob(...this.m)};RF.prototype.createGameSocket=function(){this.socket=new WebSocket(this.connectHostname);this.socket.binaryType="arraybuffer";this.pingSentTime=Date.now();this.socket.onopen=()=>{if(null!=this.socket){var a=jd(RF.list,this);this.socket.onmessage=b=>{Cc.a&&Cc.b.push([Date.now(),b.data]);ne(a,b)}}};this.socket.onclose=()=>{t.a&&t.a.close();this.close();a45()}};RA.prototype.applyUpdate=
function(a){this.x=l(a.x/10);this.y=l(a.y/10);this.exploding=l(a.exploding);this.emitting=l(a.emitting);this.emissionRadius=l(a.emissionRadius/10);this.q=0;this.timeAlive++};RA.prototype.G=function(){"landMine"==this.type||this.emitting||(this.exploding&&(this.animationFrame++,this.animationFrame<this.model.length&&this.deactivate()),this.timeAlive<this.travelTime&&(this.x+=this.spdX,this.y+=this.spdY),this.angle=(this.angle+7)%360)};RA.prototype.K=function(){if(this.activated){if(this.exploding)return a38(f,
c2,this.getAttr(),this.angle,this.model[this.animationFrame]);a38(f,c2,this.getAttr(),this.angle,this.model[0]);if("landMine"==this.type&&1==RD.pool[c3].thermal){var a=this.x-c2.x,b=this.y-c2.y;f.strokeStyle=this.ownerId==c3||0<this.teamCode&&this.teamCode==RD.pool[c3].teamCode?"#107a24":"#ff0000";j22(f,a,b,20);j22(f,a,b,4)}}};document.onkeydown=a=>{if(!Pa||a.r){var b=W.b[a.keyCode],c=RF.list[C.a],e=Za("chatboxContainer"),d=Za("chatbox");if(!j46&&!c4&&la([R.g,R.q],a.keyCode)||c4&&!j46&&(b||la(Object.values(R),
a.keyCode)))switch(a.preventDefault(),a.keyCode){case R.b:case R.l:J(C.a,0,1);J(C.a,1,0);break;case R.d:case R.m:J(C.a,1,1);J(C.a,0,0);break;case R.h:case R.n:J(C.a,2,1);J(C.a,3,0);break;case R.f:case R.o:J(C.a,3,1);J(C.a,2,0);break;case R.e:J(C.a,4,1);break;case R.k:J(C.a,5,1);break;case R.p:o10.push({type:8,content:c37=!c37,initTime:Date.now()});break;case R.g:qb.hidden=!qb.hidden;break;case R.r:db.hidden=!db.hidden;break;default:if(W.a&&b){var g=" ".repeat(hd=hd+1&1);Fb(C.a,g+b+g)}}a.keyCode==
R.j&&c4&&!c28&&Mf(c,e,d,a.shiftKey);a.keyCode==R.a&&j46&&(Eb.blur(),e.style[x]=$b,j46=0,J(C.a,7,0))}};document.onkeyup=function(a){if(c4&&!j46&&la([68,83,65,87,82,32,45,37,38,39,40],a.keyCode))switch(a.preventDefault(),a.keyCode){case R.b:case R.l:J(C.a,0,0);break;case R.d:case R.m:J(C.a,1,0);break;case R.h:case R.n:J(C.a,2,0);break;case R.f:case R.o:J(C.a,3,0);break;case R.e:J(C.a,4,0);break;case R.k:J(C.a,5,0)}};a41=()=>{let a=Date.now(),b=5,c;c4||b21||"/model"==window.location.pathname||a29();
if(null!=c3){1!==q.a&&(j7=q.a?2E3:c2.width,j8=q.a?1125:c2.height,a1());for(let z in landMine[0])landMine[0][z][1][3]=q.h?"#000":"#e8e8ed";j17=0;f.clearRect(0,0,canvas.width,canvas.height);c2.G();le(f,c2);for(let z of na(RA))z.activated&&"landMine"==z.type&&(z.G(),z.K());for(let z of na(RC))z.activated&&(z.G(),z.K());for(let z of na(RB))z.activated&&(z.G(),z.K(),z.f||z.J());for(let z of na(RA))z.activated&&"landMine"!=z.type&&(z.q||(z.q=0),z.G(),z.K());for(let z of na(RD))!z.activated||c28&&z.id==
c3||(z.G(),z.L(),z.M());for(let z of na(RA))z.activated&&z.drawEmission(f,c2);for(let z in j27){let O=j27[z];5>O.c42++?j26(c2,O.x,O.y):delete O[z]}a55(f,c2);let aa=RD.pool[c3];L.d&&(c5=aa.hp,c6=aa.armorAmount,c7=aa.score);if(ja[0]){var e=C.a,d=aa;(d.score>=c33||1<=c10)&&!o3[1]&&ja[1]&&ld(e,ja[1],1);(d.score>=c34||2<=c10)&&!o3[2]&&ja[2]&&ld(e,ja[2],2);(d.score>=c35||3<=c10)&&!o3[3]&&ja[3]&&ld(e,ja[3],3)}j9=[V.x,V.y];a9(aa);je(aa);a13(f,c8);c=me(f,j38)}a113();a56();L.j&&ge();j9[0]/=j6;j9[1]/=j5;if(L.b){var g=
b;let aa=5,z=RF.list[0]||{currentPing:"Not Connected",n:"Not Connected",p:"Not Connected",o:"Not Connected"},O=["Ping: "+z.currentPing+" ms","Avg.: "+fa(z.n)+" ms","Max:  "+z.p+" ms","Min:  "+z.o+" ms"];if(b21||c28)if(aa+=10,selfPremiumMember&&(aa+=35),b3||b4)f.font="14px Arial",aa+=zb(f.measureText((b3?"Logged in":"Playing")+" as "+b4).width);f.font="bold 16px consolas";for(let Sa=0;Sa<O.length;Sa++)$a(aa,16+17*Sa,O[Sa],"#fff");var h=aa+zb(f.measureText(O[2]).width);b=g+(h+10)}if(L.c){var m=b,T=
b;f.font="bold 16px consolas";let aa=["Render time: "+ac+"ms",Qa("FPS: ",13)+hb(1E3/ac,25*E.c).toFixed(500<ac?2:1)];$a(T,16,aa[0],"#fff");$a(T,32,aa[1],"#fff");var A=zb(f.measureText(aa[0].length>aa[1].length?aa[0]:aa[1]).width);b=m+(A+10)}if(c2){let aa=[],z=[],O=RD.pool[c3],Sa={x:O.x-c2.x,y:O.y-c2.y},eb={x:ra.x-c2.x,y:ra.y-c2.y},Lc=zb(RF.list[0].n/2.5);for(let k of na(RD))k.activated&&(q.o||k.id!=O.id)&&0!=k.hp&&aa.push(k);for(let k of na(RB))k.activated&&z.push(k);var za=O,ib=aa;let oe=[],pe=[];
for(let k of ib)k.invincible||k.teamCode&&k.teamCode==za.teamCode||(-1599485949===k.a||n.e&&k.chatBoxOpen||la(bb,k.u)||la(t.l,k.a)?pe.push(k):oe.push(k));let {y:qd,x:qe}={y:oe,x:pe};if(L.o){var Ic=b,Ha=O;f.font="bold 16px consolas";let k=["Pos: x:"+Qa(Ha.x,7)+" y: "+Qa(Ha.y,7),"Vel: x:"+Qa(Ha.spdX,7)+" y: "+Qa(Ha.spdY,7),"Acc: x:"+Qa(Ha.d.toFixed(1),7)+" y: "+Qa(Ha.e.toFixed(1),7)],G=16,Ia="";for(let Z of k)$a(Ic,G,Z,"#fff"),G+=17,Ia.length<Z.length&&(Ia=Z);zb(f.measureText(Ia).width)}if(t.j){var F=
c;f.font="bold 14px consolas";for(let k in t.k){let G=t.k[k];if(10>G.length)continue;F-=165;f.strokeStyle=f.fillStyle="#888";f.globalAlpha=.5;f.fillRect(F,5,160,160);f.lineWidth=3;f.globalAlpha=1;f.strokeRect(F,5,160,160);F+=5;let Ia=[" Name: "+G[0],"   HP: "+Qa(G[1])+"/"+G[2],"Armor: "+Qa(G[3])+"/"+G[4]," Ammo: "+Qa(G[5])+"/"+G[6],"Class: "+Bf[G[7]],"    X: "+Qa(fa(G[8]),4)+" Y: "+Qa(fa(G[9]),4)];for(let Z=0;Z<Ia.length;Z++)$a(F,20+17*Z,Ia[Z],"#000");f.lineWidth=2;for(let Z=0;3>Z;Z++)f.strokeRect(F+
5+50*Z,115,40,40),j30[G[11+Z]]&&(f.drawImage(j30[G[11+Z]],F+5+50*Z,115,40,40),1==Z&&0<G[14]&&(j58.globalAlpha=.75,j58.fillStyle="#7a7a7a",j58.fillRect(F+5+50*Z,115,40*G[14],40),f.globalAlpha=1));F-=10}}f.font="bold 20px consolas";if(dc.a){var M=C.a,ua=Sa;for(let k of[0,1,2,3])J(M,k,0);for(let k of[[1],[1,3],[3],[3,0],[0],[2,0],[2],[2,1]][fa(ab(ua.y-V.y,ua.x-V.x)/Oa*8+4)%8])J(M,k,1);ya(Sa,ra,50,2,"#444");for(let k=Oa/16;k<Oa;k+=Oa/8)Gb(O,{x:50*ha(k),y:50*ma(k)},eb,1,"#000");ec(Sa,V,ra,2,"#000")}var ba=
aa,oa=Sa,S=eb,X=Lc;for(let k of ba){k.reloading||0!=k.currentBullets||(k.currentBullets=k.maxBullets);q.c&&ec(oa,k,S,1);let G;-1599485949==k.a?(f.globalAlpha=2*Ab,G="blue"):la(t.l,k.a)?(f.globalAlpha=Ab,G="blue"):la(cb,k.u)?(f.globalAlpha=Ab,G="red"):la(bb,k.u)?(f.globalAlpha=2*Ab,G="#000"):n.e&&k.chatBoxOpen&&(f.globalAlpha=Ab,G="#000");G&&ya(k,S,1.4*k.F,5,G);f.globalAlpha=1;let Ia=k.x+S.x-k.F,Z=k.y+S.y-(k.F+6);q.j&&($a(Ia,Z,k.hp,Dc(k)),Z-=20);q.k&&($a(Ia,Z,k.armorAmount,"#666"),Z-=20);q.l&&($a(Ia,
Z,k.currentBullets+"/"+k.maxBullets,"#000"),Z-=20);q.m&&k.reloading&&$a(Ia,Z,"RELOADING "+Qa(fa(100*(k.reloadingAnimation?k.reloadingFrame/(k.reloadingAnimation.length-X):0))+"%"),"#888");if(q.t){let re=rc[k.class],Mc=bd[re]*pb[re];f.globalAlpha=1;var Y=k,Ba=S,jb=Ea((Mc*ad)**2+(.5*Mc+k.F)**2);for(let Ib=0;3>Ib;Ib++)f.globalAlpha/=2,ya(Y,Ba,jb-3*Ib,3,void 0);f.globalAlpha=1;var Jc=k,Of=S,Pf=Ea((1.5*Mc*ad)**2+(.75*Mc+k.F)**2);for(let Ib=0;3>Ib;Ib++)f.globalAlpha/=2,ya(Jc,Of,Pf-3*Ib,3,void 0);f.globalAlpha=
1}}var hc=eb;if(q.i){for(let k of na(RA)){if(!k.activated)continue;if("landMine"==k.type){ya(k,hc,20,2);continue}if(k.emitting){ya(k,hc,k.emissionRadius,2);continue}ya(k,hc,10,2);if(!q.g||k.timeAlive>k.travelTime)continue;let G=(k.travelTime-(k.timeAlive+k.q))*E.c;k.q+=Ab;Gb(k,{x:k.spdX*G,y:k.spdY*G},hc,1)}for(let k of na(RC))k.activated&&k.isKnife&&ya(k,hc,5,2)}p.c||Qb({clientX:V.x/j6,clientY:V.y/j5},1);let Rb=rc[c1.weapon];{var ic=O,jc=eb,Qf=qd,Rf=qe,Sf=z,Tf=Wd,Uf=Sa,se=Rb;let k={D:K,E:K};n.a&&
(ya(ic,jc,10,2,"#000"),n.v&&ya(ic,jc,15,2,"gray"),ic.dashing&&n.j||(k=de(ic,jc,Qf,Rf,Sf,Tf,Infinity,se),k.D&&(p.c||Qb(ee(ic,k.D,jc,k.E,se),1),q.c&&ec(Uf,k.D,jc,3))));var te=k}var pa=O,Sb=C.a,ue=Sa,kb=eb,Vf=qd,Wf=qe,Xf=z,ve=Lc;if(0<c9.current-ve||!o3[2])p.c=0,!p.a&&!p.d||p.d&&Mb[0]==o3[2]&&p.g||J(Sb,5,0);else switch(o3[2]){case Mb[3]:if(p.a){var rd=pa.F+p.b,Nc=de(pa,kb,Vf,Wf,Xf,pa.F**2,rd**2,6);ya(pa,kb,rd,3,"#f88");Nc.D&&Nc.E<rd**2?(Qb(ee(pa,Nc.D,kb,Nc.E,6),1,1),p.c?J(Sb,5,1):J(Sb,5,0),p.c=1):p.c=
0}break;case Mb[0]:b:if(p.d){var Oc=0,we=2025,xe=ve+p.i,ub=gc(pa,pa,0,0);ub.x=pa.x+(pa.x-ub.x);ub.y=pa.y+(pa.y-ub.y);p.l&1&&(ya(ub,kb,45,2,"#000"),ya(ub,kb,30,2,"#000"));for(let k of na(RC)){if(k.ownerId===pa.id||k.teamCode&&k.teamCode==pa.teamCode||900>Ra(k,pa,ra))continue;let G={x:k.spdX*xe+k.length*ma(k.angle*ia),y:k.spdY*xe+k.length*ha(k.angle*ia)},Ia=ae(k.x,k.y,k.x+G.x,k.y+G.y,ub.x,ub.y);1<p.l&&Gb(k,G,kb,1,"#ddd");Ia<we&&(Oc=k,we=Ia)}if(Oc)p.g||J(Sb,5,1),p.c=2.5*p.e,p.f=ab(-Oc.spdY,-Oc.spdX);
else if(0<p.c&&(p.c-=2.5/E.c))p.g||J(Sb,5,1);else{p.g||J(Sb,5,0);p.c=p.f=0;break b}Qb({clientX:ue.x+50*ma(p.f),clientY:ue.y+50*ha(p.f)},1,1)}break;case Mb[1]:case Mb[4]:if(p.h){let k={x:50*ma(pa.playerAngle*ia),y:50*ha(pa.playerAngle*ia)};f.strokeStyle="#000";f.lineWidth=1;f.strokeRect(pa.x+kb.x+k.x-20,pa.y+kb.y+k.y-20,40,40);Gb(pa,k,kb,1,"#000")}}if(n.a&&n.h&&n.g){let k=bd[Rb]*pb[Rb]*(o3[1]===id[8]||o3[3]===id[8]?1.5:1),G=(k*ad)**2+(.5*k+O.F)**2;ya(O,eb,Ea(G),2,"#000");te.D&&!p.c&&te.E<G&&(!n.m||
V.isPressed)?J(C.a,6,V.isShooting=1):J(C.a,6,V.isShooting=0)}B.j&&O.M(f,c2);var Ja=O,ye=eb;if(!Ja.dashing&&(B.c&&!(Ja.reloading||Ja.shooting||V.isShooting)||B.a&&Ja.reloading&&Ja.reloadingAnimation&&Ja.reloadingFrame<Ja.reloadingAnimation.length-Lc||B.b&&Ja.shooting&&Ja.shootingAnimation&&Ja.shootingFrame<Ja.shootingAnimation.length-Lc)){if(0===bc%B.g){let k=(B.d+B.e*Ud()+bc*B.f)*ia,G=2*Ja.F;B.h=Ja.x+ye.x+G*ha(k);B.i=Ja.y+ye.y+G*ma(k)}Qb({clientX:B.h,clientY:B.i},1,1)}Rb=rc[c1.weapon];let ze=(O.playerAngle+
210)*-ia,Ae=sc[Rb]+pb[Rb]-14,Be=(O.playerAngle+270)*-ia,kc={x:Sa.x+ha(ze)*O.F,y:Sa.y+ma(ze)*O.F},sd={x:kc.x+ha(Be)*Ae,y:kc.y+ma(Be)*Ae};q.f&&(Gb(kc,{x:j9[0]-kc.x,y:j9[1]-kc.y},ra,1,"#000"),ya(sd,ra,1,2,"red"));Wd=(O.x+eb.x-sd.x)**2+(O.y+eb.y-sd.y)**2;ke(C.a);!L.a||qd.length||V.isPressed||O.shooting||O.reloading||O.maxBullets==O.currentBullets?J(C.a,4,0):J(C.a,4,1);md(O,eb,aa,z)}bc++;RF.list[0]&&RF.list[0].check();ac=Date.now()-a;setTimeout(a41,40/E.c-ac)};a45=()=>{b15||a93();a4();a75();b38=b4=null;
b1=b2=b3=selfPremiumMember=0;$("#hostServerTabLi").hide();$("#playButton").hide();Ua(Za("gametypeDropdown"),{[x]:Md});Ua(Za("serversBtn"),{[x]:H});a99()};reloadGame=()=>a120(o4.server,c22);play=()=>{let a=RF.list[C.a];a!==K&&(c4||a.send(a59("c1",{class:c1.weapon,armor:c1.armor,color:c1.color})),b21=1,c8={1:0,2:0,3:0},o3={1:"",2:"",3:""},a2("c1",c1.weapon+","+c1.armor+","+c1.armorBtn+","+c1.color,365))};(()=>{let a=JSON.parse(localStorage.getItem("TioHax_settings")||"{}"),b=[[bb],[cb],[ja],[n,"abcdefghijklmnovwxy"],
[q,"abcdefghijklmnotu"],[u,"abcdejk"],[B,"abcdefgj"],[W,"abcdefgh"],[L,"abcdefghijop"],[E,"abdce"],[t,"befj"],[Bc],[p,"abdeghijkl"],[Ef,"abcd"],[v,"bcdegopqrsmijklt"],[C,"abc"]];for(let c=0;c<b.length;c++)if(K!=a[c]){let [e,d]=b[c];if(d)for(let g=0;g<d.length;g++)K!=a[c][g]&&(e[d[g]]=a[c][g]);else e.length=0,e.push(...a[c])}})();(()=>{let a=Jf("TioHax Cheat Menu",ed[0],ed[1]);document.head.append(r("style",{},{textContent:"img{"+w+":"+Q+";"+y+":"+Q+"}::-webkit-scrollbar{"+w+":"+jf+"}::-webkit-scrollbar-track{"+
Pc+":"+qa+";border-left:"+Lb+"}::-webkit-scrollbar-thumb{"+Pc+":"+We+";border-left:"+Lb+"}::-webkit-scrollbar-thumb:hover{"+Pc+":"+Ad+"}"}));qb=a[0];Db=a[2];document.body.append(qb);Pb(0);Kf();Ua(qb,{[wb]:Td(window.innerHeight-l(Db.style[y]))/2+"px"})})();document.onmousemove=a=>{if(a.isTrusted){V.x=a.clientX;V.y=a.clientY;for(let b of uc)b.enable&&Ua(b.element,{[lb]:V.x-b.offsetX+"px",[wb]:V.y-b.offsetY+"px"});ce()}};window.onresize=()=>{ce();a1();if(null!=c3){c2.G(1);le(f,c2);for(var a of na(RA))(a.activated||
"landMine"==a.type)&&a.K();for(let c of na(RC))c.activated&&c.K();for(let c of na(RB))c.activated&&c.K();for(let c of na(RA))c.activated&&"landMine"!=c.type&&c.K();for(let c of na(RD))!c.activated||c28&&c.id==c3||(c.L(),c.M());for(let c of na(RA))c.activated&&c.drawEmission(f,c2);for(var b in j27)a=j27[b],5>a.c42?j26(c2,a.x,a.y):delete a[b];a55(f,c2);j9=[V.x,V.y];b=RD.pool[c3];a9(b);je(b);a13(f,c8);me(f,j38);ge()}};a36=a119=a78=a79=a80=()=>{};for(let a of j36){let b=Za(a.pl);b&&b.remove()}c2&&=new RE(c2);
document.onmouseup=()=>{};document.onmousedown=()=>{};canvas.onmouseup=a=>{!j17&&c3&&1==a.which&&(V.isPressed=0,J(C.a,6,V.isShooting=0));j18={x:0,y:0}};canvas.onmousedown=a=>{if(!($("#loginModal").is(":visible")||$("#registerModal").is(":visible")||$("#aboutModal").is(":visible")||$("#privacyModal").is(":visible")||(j18={x:a.clientX,y:a.clientY},j17||null==c3))){var b="";if(1!==a.which&&(n.n||n.o)){a:if(1>j3&&2.6<j3)var c="";else{b=.03;var e=1.7*j13;for(c of j38.current){if(!c.userId)continue;let d=
(.05+b)*j14;b+=.045;if(a.x>e&&a.y>d&&a.x<e+.295*j13&&a.y<d+.04*j14){c=sb(c.userId);break a}}c=void 0}if(!c)a:{c=RD.pool[c3];b=c2.x+a.x/j6;e=c2.y+a.y/j5;for(let d of na(RD))if(d.activated&&d.id!=c.id&&Ra(d,{x:b,y:e},ra)<=(d.F+2)**2){c=d.u;break a}c=void 0}b=c}switch(a.which){case 1:!n.m&&n.a&&n.g||J(C.a,6,V.isShooting=1);V.isPressed=1;break;case 2:(a=b)&&n.n?(Hb(cb,a),la(bb,a)&&Hb(bb,a)):(n.v=1-n.v,Fa());break;case 3:(a=b)&&n.o?(Hb(bb,a),la(cb,a)&&Hb(cb,a)):(n.a=1-n.a,Fa())}n.a||(Qb({clientX:V.x,clientY:V.y}),
ke(C.a))}};canvas.onwheel=a=>{1==q.a&&(a.preventDefault(),a=qc(a.deltaY),1==a&&(j7*=q.u,j8*=q.u),-1==a&&(j7/=q.u,j8/=q.u),a1())};window.onbeforeunload=a=>{if(b3&&!L.f)return a.preventDefault(),a.returnValue="You're still logged in. Are you sure you want to leave?"};RF.list&&RF.list[0]&&RF.list[0].socket&&RF.list[0].socket.url==RF.list[0].connectHostname&&(RF.list[0].socket.onmessage=function(a){Cc.a&&Cc.b.push([Date.now(),a.data]);ne(0,a)});for(let a of na(RD))a.activated&&(a.F=a.radius,a.H=a.hpRadius,
a.d=a.e=0,fe(a,a.username));Za("reconnectButton").style[x]==Md&&reloadGame();Ua(Za("playButton"),{[y]:Id,[lc]:da,[ud]:oc});Ua(Za("reconnectButton"),{[y]:Id,[lc]:da,[ud]:oc,[Ce]:Ne})})();
